### ISSUE TITLE
asPercent seems to misbehave

### ISSUE THREAD

**Issue by grobian** [go-graphite/carbonapi#115]
http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.asPercent

When used with two metrics and no value to determine the 100%, carbonapi draws a 100% value, graphite-web draws two lines with the corresponding percentage calculations based on the sum of both.

**Comment by dgryski** [comment]
I can't reproduce this.

**Comment by dgryski** [comment]
I have a failing test case now.

**Comment by Civil** [comment]
Can you please share the test case?

**Comment by Civil** [comment]
It looks bug is extremely old and since then asPercent received a bunch of bug fixes, so closing that.
