### ISSUE TITLE
Support for color templates

### ISSUE THREAD

**Issue by oriordan** [go-graphite/carbonapi#163]
Graphite had support for different color templates in graphTemplates.conf, using &template=<templatename> parameter. Carbonapi currently doesn't support this (and I'm not sure it should, really), but as discussed raising a case for it.

Note that this feature was removed in latest graphite (according to the docs), and has been replaced with something completely different (http://graphite.readthedocs.io/en/latest/render_api.html#template) which might be nice to support.

**Comment by Civil** [comment]
Sorry that it took so long to fix.

Current master (and upcoming 0.10 release) supports that functionality. Though carbonapi can't parse graphite's graphTemplates as-is, you need to convert them from ini-style to toml (that's pretty easy though).
