### ISSUE TITLE
timeShift() needs resetEnd=False

### ISSUE THREAD

**Issue by dgryski** [go-graphite/carbonapi#166]
Consider:  `target=metric&target=timeshift(metric, '24h')&from=midnight&until=tomorrow`

that should display 1d of data from midnight to midnight, with metric graphed as much as we have, overlaid on all of yesterday's data.

**Comment by dgryski** [comment]
Turns out this works.  I need to hunt down the (internal) query that was failing and resimplify it.

**Comment by Civil** [comment]
Can you provide more information about that? So I'll be able to fix that.

**Comment by dgryski** [comment]
Docs for timeshift http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.timeShift

IIRC we don't support `resetEnd=false`

**Comment by nnuss** [comment]
> If resetEnd is False, will instead draw full range including future time.

My read of the doc is the opposite. That we always behave like `resetEnd=false`.
I'm also experiencing graphite (0.9.12) draws the same graph for **both** `false` and `true` (with undefined implying the default of `resetEnd=true`).

**Comment by dgryski** [comment]
That's entirely possible :D  I just remember seeing a graph that was using `resetEnd` and noticing that our code did the WrongThing.   In either case, our code is incomplete with respect to upstream graphite-web.

**Comment by Civil** [comment]
I think that was actually fixed in #543 long time ago.
