### ISSUE TITLE
Current master seems to always force caching and return no results

### ISSUE THREAD

**Issue by fiskn** [go-graphite/carbonapi#198]
Spent a few hours scratching my head on this one. Reverting to 0.7.0 has fixed the problem.

No matter if caching is set to null or mem, no results were being returned to grafana. Also no request was being made to zipper/carbonserver. It seemed carbonapi cache was incorrectly responding from its cache even though there were no results cached.

I captured a tcpdump of the request and starting testing with curl. Only once I passed the nocache=1 parameter in the request did I get anything back.  Once I had a successful query, setting nocache=0 allowed the same query to return results.

**Comment by dgryski** [comment]
Yes. I need to revert a bunch of the code from this week. I was experimenting with more caching for the zipper and made some changes here too. Sorry about that. Please use the last tagged release.

**Comment by Civil** [comment]
At this moment latest tagged release is what we run in production for a while. Master might be unstable, with some experiments going, etc.

**Comment by dgryski** [comment]
This was probably fixed with https://github.com/go-graphite/carbonapi/commit/68ccaf214d23ca0861a8f20381370fef4f750293
