### ISSUE TITLE
support groupByNodes()

### ISSUE THREAD

**Issue by ikruglov** [go-graphite/carbonapi#201]
groupByNodes(seriesList, callback, *nodes)
Takes a serieslist and maps a callback to subgroups within as defined by multiple nodes

&target=groupByNodes(ganglia.server*.*.cpu.load*,"sumSeries",1,4)
Would return multiple series which are each the result of applying the “sumSeries” function to groups joined on the nodes’ list (0 indexed) resulting in a list of targets like

sumSeries(ganglia.server1.*.cpu.load5),sumSeries(ganglia.server1.*.cpu.load10),sumSeries(ganglia.server1.*.cpu.load15),sumSeries(ganglia.server2.*.cpu.load5),sumSeries(ganglia.server2.*.cpu.load10),sumSeries(ganglia.server2.*.cpu.load15),...

**Comment by towolf** [comment]
https://github.com/go-graphite/carbonapi/pull/232

@Civil can this be closed then?

**Comment by nnuss** [comment]
Indeed. Closed by #232
