### ISSUE TITLE
divideSeries differs from graphite-web: requires single dividendSeries when divisorSeries present

### ISSUE THREAD

**Issue by cldellow** [go-graphite/carbonapi#203]
The graphite docs suggest that this function can take a series list for the dividends:

```
divideSeries(dividendSeriesList, divisorSeries)
Takes a dividend metric and a divisor metric and draws the division result. 
```

And in fact, in graphite-web, you can do:

```
divideSeries(numerators.*, divisor)
```

and get N series back, where each series is the result of dividing one of the series in `numerators.*` by the `divisor` series.

That's not supported in carbonapi: https://github.com/go-graphite/carbonapi/blob/master/expr/expr.go#L1097 explicitly prohibits it.

Is that intentional? If not, I can try to put together a patch sometime this week. I think it should be possible to support this case while also supporting carbonapi's extended divideSeries use case in https://github.com/go-graphite/carbonapi/commit/e0a9a60d48fe83f7ac685d3bd08fa18b41a88578.

**Comment by dgryski** [comment]
We woul welcome a patch for to enable this functionality.
