### ISSUE TITLE
Merge CarbonAPI with Carbonzipper

### ISSUE THREAD

**Issue by Civil** [go-graphite/carbonapi#208]
Now as zipper is now a package, we can make carbonapi use this library and talk directly to the storages.

This will simplify complexity of the system.

**Comment by StephenPCG** [comment]
I wondered a long time why zipper and api are separate binaries. Finally you're merging them :)

**Comment by Civil** [comment]
Yes, I think most if not all preparations was done during zipper's 0.70 release.

**Comment by Civil** [comment]
current master have an option 'upstreams' that basically is the zipper (same library)
