### ISSUE TITLE
Small images don't render data points properly

### ISSUE THREAD

**Issue by DamianZaremba** [go-graphite/carbonapi#210]
While trying to use small carbonapi rendered images as 'spark line' graphs, I noticed a strange behaviour in carbonapi. It seems to be related to the graph-offset/padding.

To replicate the problem:
* /render/?height=20&target=constantLine(1)&graphOnly=1 - Displays a blank graph (broken)
* /render/?height=20&target=constantLine(1) - Displays the line as expected
* /render/?height=50&target=constantLine(1)&graphOnly=1 - Renders the line, with a lot of space above it (sort of working)

For some (seemingly unrelated reason) the python carbonapi seems to refuse to render a constantLine in any form.... but using 'real data' at different scales (values in the 10s, 100s, 1000s) this can be replicated.

An example of this issue is as below;
Standard API:  ![graphite-render](https://cloud.githubusercontent.com/assets/142120/25555430/dcf85b96-2ce6-11e7-90c9-7133ed1a72f2.png)

Carbon API:  ![carbon-api-render](https://cloud.githubusercontent.com/assets/142120/25555431/dfcf8218-2ce6-11e7-88b7-c72a8af99dc8.png)

**Comment by dgryski** [comment]
Spark-line-like graphs have been successfully rendered in the past.  We'll have to see what the difference is...

**Comment by Civil** [comment]
Should be fixed in current master. Please reopen if it's still an issue.
