### ISSUE TITLE
Packages for Debian (stretch) missing 

### ISSUE THREAD

**Issue by skorpy2009** [go-graphite/carbonapi#228]
Hey, is there a chance for a Debian package repo? Specially for stable / stretch?

**Comment by Civil** [comment]
For now you can use Ubuntu 16.04 packages, as it's a Go code, it should be compatible with Debian too.

I'll add autobuilds for Debian Jessie, Stretch and Buster before next major release (still don't have any ETA for that).

**Comment by Civil** [comment]
https://packagecloud.io/app/go-graphite/autobuilds/search?dist=debian%2Fstretch
https://packagecloud.io/app/go-graphite/autobuilds/search?dist=debian%2Fjessie
https://packagecloud.io/app/go-graphite/autobuilds/search?dist=debian%2Fbuster
