### ISSUE TITLE
[Feature Request] Implement divideSeriesLists() function

### ISSUE THREAD

**Issue by timtofan** [go-graphite/carbonapi#231]
Please implement divideSeriesLists() function.

**Comment by nnuss** [comment]
Reference docs:
http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.divideSeriesLists

Graphite implementation:
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L619

**Comment by towolf** [comment]
Yeah, needed this today too.

**Comment by Civil** [comment]
Seems to fixed by PR #233
