### ISSUE TITLE
build with cairo support fails

### ISSUE THREAD

**Issue by mlausch** [go-graphite/carbonapi#237]
Hi,

I try to build carbonapi with cario support on my gentoo machine but the build fails with following error

# carbonapi/vendor/github.com/evmar/gocairo/cairo
could not determine kind of name for C.Display
could not determine kind of name for C.Drawable
could not determine kind of name for C.Pixmap
could not determine kind of name for C.Screen
could not determine kind of name for C.Visual
could not determine kind of name for C.cairo_xlib_device_debug_cap_xrender_version                                                                                                                    
could not determine kind of name for C.cairo_xlib_device_debug_get_precision                                                                                                                          
could not determine kind of name for C.cairo_xlib_device_debug_set_precision                                                                                                                          
could not determine kind of name for C.cairo_xlib_surface_create                                                                                                                                      
could not determine kind of name for C.cairo_xlib_surface_create_for_bitmap                                                                                                                           
could not determine kind of name for C.cairo_xlib_surface_get_depth
could not determine kind of name for C.cairo_xlib_surface_get_display
could not determine kind of name for C.cairo_xlib_surface_get_drawable
could not determine kind of name for C.cairo_xlib_surface_get_height
could not determine kind of name for C.cairo_xlib_surface_get_screen
could not determine kind of name for C.cairo_xlib_surface_get_visual
could not determine kind of name for C.cairo_xlib_surface_get_width
could not determine kind of name for C.cairo_xlib_surface_set_drawable
could not determine kind of name for C.cairo_xlib_surface_set_size

Maybe on my Host is something missing. I need some help to fix this issue.

go version go1.8.3 linux/amd64
cairo-1.14.8

**Comment by Civil** [comment]
Please ensure that cairo is built with at least USE="X xcb" (I understand that having X on a server is not a good idea, but that's how the gocario/cairo bindings were written).

**Comment by mlausch** [comment]
This answer was fast. I added the use flags to cairo and now it is working.
Tank you.

**Comment by Civil** [comment]
You welcome :)

Feel free to ask any questions about carbonapi or other parts of our stack.
