### ISSUE TITLE
Add support for graphouse backend

### ISSUE THREAD

**Issue by s3rj1k** [go-graphite/carbonapi#244]
It would be nice to have native support for graphouse backend
https://github.com/yandex/graphouse

**Comment by Civil** [comment]
I see no reason to add support of graphouse at this moment. It's better to add support of Carbonzipper protobuf apj to graphouse.
Also if you want to use carbonapi with clickhouse as a backend, please consider using https://GitHub.com/lomik/carbon-clickhouse

**Comment by Civil** [comment]
I've introduced pluggable backends in recent versions of carbonzipper (underlying library that we use to query backends).
Currently it supports our own protocol (old and new version), gRPC-based protocol and msgpack (in a way metrictank supports that).

Feel free to send a PR adding graphouse support there.
