### ISSUE TITLE
field list in accessLogger for cached requests

### ISSUE THREAD

**Issue by azhiltsov** [go-graphite/carbonapi#246]
accessLogger for requests from cache has different set of fields in the log. 
For instance referer field is missed.
Set of fields need to be the same.

**Comment by Civil** [comment]
As a global todo thing - maybe we should have something like state, strictly structured, populated and just print it out to the log.

**Comment by azhiltsov** [comment]
Same set of fields across all stack sounds good to me

**Comment by Civil** [comment]
It seems like this is obsolete now.
