### ISSUE TITLE
Bool value parsed as name type

### ISSUE THREAD

**Issue by borovskyav** [go-graphite/carbonapi#260]
Hi! When i use expr.EvalExpr function on targets with graphite function like summarize (for example, aliasByNode(summarize(sortByTotal(exclude(wildcard.*.here, 'AdminTools')), '5min', 'sum', false), 5, 7, 8)), EvalExpr builds me tree with false leaf of type 'name'. Then i use expr.Metrics() on this tree, method returns me two metrics: 
1. wildcard.*.here
2. false

It breaks system for us, because we want to index our targets by this metrics.

**Comment by dgryski** [comment]
Probably need to fix code at https://github.com/go-graphite/carbonapi/blob/master/expr/expr.go#L59 to allow different functions to respond which of their arguments are metrics.  Alternately we can change the boolean type from etName to etBool or something.  That might be easier.
