### ISSUE TITLE
group() does not work then one of seriesLists has no methods.

### ISSUE THREAD

**Issue by borovskyav** [go-graphite/carbonapi#261]
I use target like this <code>group(aliasByNode(summarize(sortByTotal(exclude(First.metrics.*.wildcard, 'AdminTools')), '5min', 'sum', false), 5, 7, 8), alias(summarize(sumSeries(exclude(Second.metrics.*.wildcard, 'AdminTools')), '5m', 'sum', false), 'Total')) </code>
Then i fix one of this target wildcard metrics so that they will not have metrics (for example <code>First.metrics.*.wildcard</code> has metrics -> <code>Third.metrics.*.wildcard</code> no metrics) then carbon-api will return no data points.

**Comment by Civil** [comment]
Can you please check if it's already fixed here:
https://github.com/go-graphite/carbonapi/issues/225
