### ISSUE TITLE
carbonapi serves an error when the metric name starts with a digit

### ISSUE THREAD

**Issue by alexandreboisvert** [go-graphite/carbonapi#278]
Hello,

Here is the description:

Metric names:

`AAAA.BBBB.CCCC (this is OK)`
`AAAA.1BBBB.CCCC (also OK)`
`1AAAA.BBBB.CCCC (this fails)`

The error message in Grafana:

> Bad Request
Target              : 1AAAA.BBBB.CCCC
Parsed so far       : 1
Could not parse     : AAAA.BBBB.CCCC

On the carbonapi server, this is the error message in the log (sanitized):

`Jan 16 11:31:45 utemplate carbonapi[4297]: 2018-01-16T11:31:45.889-0500        ERROR        access        request failed        {"handler": "render", "carbonapi_uuid": "82f42d...", "username": "", "url": "/render", "peer_ip": "...", "peer_port": "", "host": "...:8082", "referer": "http://...:3000/dashboard/db/d1?refresh=30s&panelId=3&fullscreen&edit&orgId=1", "format": "json", "use_cache": true, "targets": ["AAAA.1BBBB.CCCC", "AAAA.BBBB.CCCC", "1AAAA.BBBB.CCCC"], "from_raw": "-1h", "until_raw": "now", "from": 1516116705, "until": 1516120305, "tz": "", "cache_timeout": 60, "send_globs": false, "send_globs": false, "reason": "Bad Request\n\nTarget              : 1AAAA.BBBB.CCCC\nParsed so far       : 1\nCould not parse     : AAAA.BBBB.CCCC\n", "runtime": 0.006874933, "http_code": 400}`

Only the metric name starting with a digit creates the error.

I am not a Go developer, but the error seems to come from the function ParseExpr in [expr.go](https://github.com/go-graphite/carbonapi/blob/master/expr/expr.go).

Thank you for any feedback on this issue.

**Comment by dgryski** [comment]
Yes, my parser assumes metric names begin with a digit. We can fix that without too much trouble.

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonapi/tree/v0.9 - also if you prefer to use 0.9-like version without all refactoring thing going on.

I'll try (but won't promise) to backport all big bugfixes to v0.9 branch too and release 0.9.1 at some point in future.
