### ISSUE TITLE
aliasSub, regexp applied only to a part of a query string

### ISSUE THREAD

**Issue by alchuk** [go-graphite/carbonapi#290]
The next query always returns "dns.snake.sql_updated" as a metric name (target) whatever the second metric within the diffSeries() is.

aliasSub(diffSeries(dns.snake.sql_updated, dns.snake.zone_updated), '.*dns\.([^.]+)\.zone.*', '\1 diff to sql')

**Comment by kartoffelheinz** [comment]
Been bitten by this one, too. 

Query:
aliasSub(holtWintersConfidenceBands($host.load.load.longterm, 6), 'holtWintersConfidence(Upper|Lower).*', '\1 Limit')

Used to return "Upper Limit" or "Lower Limit" using graphite-api. Will just return host.load.load.longterm using carbonapi. 

Any progress so far?

**Comment by Civil** [comment]
Should be fixed in master.
