### ISSUE TITLE
graphite-web/api fallback

### ISSUE THREAD

**Issue by Civil** [go-graphite/carbonapi#294]
It seems to make sense to implement graphite-web fallback.

We can use functions list api to get list of functions from graphite-web, compare arguments and fallback only on stuff that's unsupported by us or where implementation knows to be different (if a url parameter or config flag is defined)

To make it easier to identify incompatibilities we might also want to allow people to specify whitelist of functions to apply or to proxy (this is TBD).

**Comment by Civil** [comment]
@Dieterbe just in case you have any comments on this

**Comment by Civil** [comment]
we might reuse the same approach as metrictank did (reverse proxy, same url parameters)

**Comment by lomik** [comment]
how about just return 501 error code? fallback can be maintained in nginx config

**Comment by Dieterbe** [comment]
+1 for proxy built-in..very simple and fast

**Comment by Civil** [comment]
Initial implementation can be found here: https://github.com/go-graphite/carbonapi/commit/2d1485e0f28f709ba1f4d8dcbaad11e2b6759b1e

For now it's done not as proxy, but as http client.
