### ISSUE TITLE
Problem with /metrics/find and globbing

### ISSUE THREAD

**Issue by vedranf** [go-graphite/carbonapi#311]
Hello,

I'm using go-carbon, graphite-api with grafana and I'm trying to replace the graphite-api with carbonapi, but it fails with /metrics/find in combination with globbing (without globbing it works, but I need it for my dashboards to work). For example, this is query that grafana send and the response from graphite-api:

$ curl 'http://localhost:80/metrics/find/?query=collectd.xy.d5*.cpu--average.*' | jq .
[
  {
    "text": "cpu-idle",
    "expandable": 0,
    "leaf": 1,
    "id": "collectd.xy.d5*.cpu--average.cpu-idle",
    "allowChildren": 0
  },
  {
    "text": "cpu-interrupt",
    "expandable": 0,
    "leaf": 1,
    "id": "collectd.xy.d5*.cpu--average.cpu-interrupt",
    "allowChildren": 0
  },
...
]

Yet the same request sent to carbonapi yields with empty list:

$ curl 'http://localhost:80/metrics/find/?query=collectd.xy.d5*.cpu--average.*' | jq .

[]

If I remove the first glob * and leave the last one, then it works. Does carbonapi support globbing in the middle or just at the end of the query string? 

Thanks,
Vedran

**Comment by Civil** [comment]
It just passes this request to go-carbon's carbonserver module and consume's it's output. That might be actually a bug there. Can you please share following information
1. Version of carbonapi you are running?
2. Version of go-carbon?
3. Can you also enable "debug" log in carbonapi and post it here?

**Comment by vedranf** [comment]
Hello,

1. 0.10.0.1 per debian package version
2. 0.12.0 per debian package version
3. This is all I get:

2018-03-30T13:19:01.333Z        INFO    access  request served  {"data": {
"handler":"find",
"carbonapi_uuid":"fa8713d1-c220-45a1-9d4a-97df9418021b",
"url":"/metrics/find/?query=collectd.xy.d*.cpu--average.cpu-*",
"peer_ip":"127.0.0.1",
"peer_port":"41082",
"host":"localhost:8081",
"runtime":0.002022396,
"http_code":200,
"uri":"/metrics/find/?query=collectd.xy.d*.cpu--average.cpu-*"
}}

with 

    - logger: ""
      file: "carbonapi.log"
      level: "debug"
      encoding: "console"

**Comment by azhiltsov** [comment]
I can replicate it with 
carbonapi - 13ebf4af4b68
carbonzipper - 8e25876573b0
go-carbon - aaa8472

However it works exactly the same way as graphite 0.9.12

**Comment by lindsaylandry** [comment]
i have also been able to replicate this with go-carbon, carbon-relay-ng, and carbonapi. I can run the wildcard query just fine if i use graphite-web, but i find it to be incredibly slow. A fix would be greatly appreciated!

**Comment by lindsaylandry** [comment]
i was able to query for wildcards with the following setting in go-carbon.conf

```
[carbonserver]
trigram-index = false
```

this was originally set to true, and would return empty results for wildcard queries.

**Comment by azhiltsov** [comment]
We noticed that this is reproducible only during initial trigram index build (after go-carbon restart) and return find results fine after some time. 
The time it takes to build the index is exposed in carbonserver.index_build_time_ns metric. 
Can you please confirm that you have the same behavior and it works fine once the index built?

**Comment by Civil** [comment]
As it seems that the issue was on go-carbon side, closing it now.

Currently I'm not sure how it would be possible to improve situation only on carbonapi side.
