### ISSUE TITLE
latest autobuild packages always use ?format=protobuf3 and incompatible with graphite-clickhouse

### ISSUE THREAD

**Issue by Slach** [go-graphite/carbonapi#313]
i use following carbonapi config
https://github.com/Slach/clickhouse-metrics-grafana/blob/master/carbonapi/carbonapi.yaml
and following clichouse-graphite config
https://github.com/Slach/clickhouse-metrics-grafana/blob/master/graphite-clickhouse/graphite-clickhouse.conf

when i try use 
```
      wget -q -O- https://packagecloud.io/go-graphite/autobuilds/gpgkey | apt-key add -
      curl -sSf "https://packagecloud.io/install/repositories/go-graphite/autobuilds/config_file.list?os=ubuntu&dist=xenial&source=script" > /etc/apt/sources.list.d/go-graphite.list
```

carbonapi always request clickhouse-graphite with ?format=protobuf3 instead of format=protobuf
and clickhouse-graphite always return emtpy response

i try use "carbonapi_v2_pb" and "auto" as protocol field on backendsv2 section, without any effect

**Comment by RudW0lf** [comment]
I have the same issue with last build. Despite in configuration string    `protocol: "protobuf"` or `protocol: "carbonapi_v2_pb"`
carbonapi still make requests to new protocol:
`2018-06-14T10:37:01.569-0400    DEBUG   zipper  got slot        {"type": "protoV2Group", "name": "http://127.0.0.1:9091", "action": "query", "server": "http://127.0.0.1:9091", "name": "http://127.0.0.1:9091", "uri": "http://127.0.0.1:9091/render/?format=protobuf3&from=1528965421&target=metric.name&until=1528987021"}`

**Comment by RudW0lf** [comment]
It looks like the error here:
https://github.com/go-graphite/carbonapi/blob/eb455333490fd8b13adde45926387d0ef1ac415e/vendor/github.com/go-graphite/carbonzipper/zipper/protocols/v2/protobuf_group.go#L123

**Comment by Civil** [comment]
Should be fixed in master.
