### ISSUE TITLE
timeShift is borked

### ISSUE THREAD

**Issue by gunnihinn** [go-graphite/carbonapi#319]
Trying to plot `divideSeries($metric, timeShift($metric, $whatever_time_period))` returns nothing in the current `HEAD` of carbonapi. We've tracked this down to that while we make requests for both time periods to zipper, we only get a response back for one of them.

Plotting all three metrics at once -- `$metric`, `$timeShift($metric, $whatever_time_period)` and `divideSeries(#A, #B)` -- gives the correct result.

It's not know when this bug was introduced. It is not present in the Python implementation of Graphite.

**Comment by hadret** [comment]
I think I'm experiencing something similar. I'm using `0.11.0-27-g89052e` of `carbonapi` and am unable to graph **anything** with the `timeShift` function, for example: `render/?target=timeshift($metric,"24h")` or `render/?target=timeshift($metric,"+1d")`.

**Comment by hadret** [comment]
Just confirmed that downgrading to `0.10.0.1` solves my problem, so there was some kind of regression with `0.11.0` release.

**Comment by gunnihinn** [comment]
@hadret Could it be that you're running into the bug fixed in ff243eb0001c88d8fe41f51c6b1f7a2519c98068?

**Comment by hadret** [comment]
@gunnihinn yes indeed, it looks like it. I will try to test it out against master then, thanks a lot!

**Comment by gunnihinn** [comment]
On closer inspection, this appears to be a problem with `divideSeries`. Calling either
```
divideSeries($metric1,$metric2)
divideSeries($metric1,$metric1)
```
for any metrics returns nothing.

The tests for `divideSeries` pass though. Odd.

**Comment by gunnihinn** [comment]
In fact, `divideSeries` is fine and the problem is somewhere in how we fetch data for timeshifted metrics. I'd incorrectly concluded that divideSeries was at fault because one of the metrics I was querying when trying to triangulate the problem was bad, and I didn't try my queries with different metrics which would have shown this was a red herring.

There's definitely one problem in how we fetch metrics in [protobuf_v2](https://github.com/go-graphite/carbonzipper/blob/master/zipper/protocols/v2/protobuf_group.go#L124:L125). The start- and stopTimes are not the same for all metrics if we timeshift some of them.

There is a similar problem somewhere in [protobuf_v3](https://github.com/go-graphite/carbonzipper/blob/master/zipper/protocols/v3/protobuf_group.go#L106) as well, as staring at things in `delve` shows that the requests we send in there look fine, but the deserialized responses are incorrect. I'm less sure about what the underlying issue is there.

**Comment by gunnihinn** [comment]
We're getting closer to finding out what's wrong here. There are at least two problems going on, and they don't seem to be entangled so far.

The one that's easier to describe is that `go-carbon` doesn't correctly reply to render requests that use version 3 of the protobuf protocol and have metrics that start- and end and different times. See [issue 237](https://github.com/lomik/go-carbon/issues/237) in its github repo.

The other one is that somewhere after commit 0832acfc58259caa32479b6fc96da10f25bec3f7 to carbonapi, these queries also broke in version 2 of the protocol. Bisecting the issue shows that commit 490d1f3266406cfe4d484d64d0eac61d5017145f is bad, and the problem could have been introduced in that commit or any of the 10 commits between them that either don't compile or throw runtime panics. The root cause there is us being too clever; the good commit makes a render request for every metric separately, while the bad ones group multiple requests together and suffer from a bug similar to the one on the `go-carbon` side. 

That bug now lives in the carbonzipper part of the code; see [issue 63](https://github.com/go-graphite/carbonzipper/issues/63) in its repo (or go directly [here](https://github.com/go-graphite/carbonzipper/blob/master/zipper/protocols/v2/protobuf_group.go#L124:L125) for the money shot).
