### ISSUE TITLE
Do we want to merge carbonapi.git and carbonzipper.git?

### ISSUE THREAD

**Issue by gunnihinn** [go-graphite/carbonapi#321]
This is for the community to discuss and decide.

Vladimir's recent patches have been aimed at integrating carbonapi and carbonzipper more. Speaking for myself, it's by now a bit frustrating to debug things in carbonapi that interact with carbonzipper, as any change to carbonzipper needs to be made inside the `vendor` directory in carbonapi.

If people aren't very against it, I'm willing to merge the carbonzipper.git repo into carbonapi.git, while maintaining the history of the latter, and set things up so we can build binaries for either program from carbonapi.git.

**Comment by Civil** [comment]
I have no objections to that and I have nothing against mega repos :) the only reason (from.my point of view) why to keep.them apart is historical reasons.

**Comment by deniszh** [comment]
Some people are still using `carbonzipper` as a separate tool. I think it's fine if it will be possible to build carbonzipper separately.

**Comment by Civil** [comment]
Also we need to be sure that there are proper redirect and/or explanation left there

**Comment by gunnihinn** [comment]
Just so we're clear, what I'm suggesting is:

- Merge the two repositories while preserving Git history, as in https://stackoverflow.com/a/10548919/1569492
- Create `cmd/carbonapi` and `cmd/carbonzipper` directories to hold each project's `main` package
- Add `carbonapi` and `carbonzipper` make targets that build those binaries
- Delete the *vendored* version of carbonzipper from carbonapi
- Resolve any conflicts that appared after that last step

I'd also investigate if we can migrate the Github issues from the carbonzipper repo into the carbonapi one, and setup redirects as Vladimir describes.

**Comment by Civil** [comment]
LGTM :)

**Comment by gunnihinn** [comment]
All right. This is on my stack now. I'll finish up some in-progress tasks and then see if I can't hammer this out.

**Comment by Civil** [comment]
Closing issue as zipper is now merged with carbonapi
