### ISSUE TITLE
applyByNode counts node from 1, not 0

### ISSUE THREAD

**Issue by limpasha** [go-graphite/carbonapi#333]
The example here:
https://github.com/go-graphite/carbonapi/blob/490d1f3266406cfe4d484d64d0eac61d5017145f/expr/expr.go#L54

already shows the problem. In Graphite [doc](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.applyByNode) the node num is supposed to point to the place where metric's uniq prefix should stop, e.g. for name `zero.one.*.three` node `2` points to the asterisk and the uniq prefix would be `zero.one.{something}.`

Looks like the problem is here:
https://github.com/go-graphite/carbonapi/blob/490d1f3266406cfe4d484d64d0eac61d5017145f/expr/rewrite/applyByNode/function.go#L57

**Comment by Civil** [comment]
This was fixed in current master by #456
