### ISSUE TITLE
substr() returns 'stop out of range' when using negative integers for start/stop

### ISSUE THREAD

**Issue by petecheslock** [go-graphite/carbonapi#338]
Using version `0.10.0.1` of carbonapi

When making a query using the `substr()` function and using negative integers for either start or stop - carbonapi returns `out of range` 

Below is an output from grafana showing empty array returned
```
xhrStatus:"complete"

request:Object
method:"POST"

data:"target=substr(test.herp.random.diceroll%2C%201%2C%20-1)&from=-30min&until=now&format=json&maxDataPoints=1432"

response:Array[0]
```

and the log from carbonapi 
```
{"level":"ERROR","timestamp":"2018-07-05T18:40:47.755Z","logger":"access","message":"request failed","data":{"handler":"render","carbonapi_uuid":"d841c6bd-07dd-49cf-bfa3-f29b92b5fb2c","url":"/render","peer_ip":"<ip>","host":"<ip>:8081","referer":"https://grafana","format":"json","use_cache":true,"targets":["substr(test.herp.random.diceroll, 1, -1)"],"cache_timeout":10,"metrics":["test.herp.random.diceroll"],"have_non_fatal_errors":true,"runtime":0.001186688,"reason":"stop out of range","from":1530814247,"until":1530816047,"from_raw":"-30min","until_raw":"now","uri":"/render","zipper_requests":1}}
```

**Comment by Civil** [comment]
What's the graphite-web's behavior for substr?

**Comment by deniszh** [comment]
Oh, I tested that specifically - it is usual python slice, e.g. substr(a.b.c.d, -1) = d

**Comment by petecheslock** [comment]
With graphite-web if I do: `substr(test.herp.random.diceroll, 0, -1)` the target in the returns as `test.herp.random` But via carbonapi I just get the out-of-range.  This is with Graphite web `1.0.2`

**Comment by deniszh** [comment]
https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L2504-L2507
