### ISSUE TITLE
Invalid types on KeepLastValue (even when proxied)

### ISSUE THREAD

**Issue by tehlers320** [go-graphite/carbonapi#347]
Build: latest master 5379139bf43f6b30939553f7f2247511627568da (i am on the bleeding edge for msgpack support)
Configuration (with proxy enabled): 
```
cat /etc/carbonapi/carbonapi-graphiteWeb.yaml
# to maintain backward compatibility, this function is disabled by default
enabled: true
# roundrobin will be used in case multiple URLs are specified
### Dont use ?format=msgpack here it doesnt work
fallbackUrls:
    - http://localhost:80
# if enabled, function will also check if supported parameters are the same
strict: false
# specify max amount of connections per each instance of graphit-web
maxConcurrentConnections: 100
# specify request timeouts
timeout: "90s"
keepAliveInterval: "30s"
# Uncomment to make those functions force-proxied to graphite-web
### keepLastValue doens't work with when setting the "INF" value grafana sets by default
forceAdd:
  - "keepLastValue"
```

When proxied to graphite-web:
```
runtime error: invalid memory address or nil pointer dereference
goroutine 98 [running]:
net/http.(*conn).serve.func1(0xc4202dc000)
        /usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0xc78940, 0x1436610)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/go-graphite/carbonapi/expr/types.ConsolidateJSON(0x3c0, 0xc4200b1100, 0xc8, 0xe0)
        /go/src/github.com/go-graphite/carbonapi/expr/types/types.go:76 +0x37
main.renderHandler(0xe26b20, 0xc4201a85a0, 0xc420156500)
        /go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http_handlers.go:385 +0x234e
net/http.HandlerFunc.ServeHTTP(0xdaba48, 0xe26b20, 0xc4201a85a0, 0xc420156500)
        /usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x14834c0, 0xe26b20, 0xc4201a85a0, 0xc420156500)
        /usr/local/go/src/net/http/server.go:2337 +0x130
github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1(0xe27860, 0xc42013e000, 0xc420156500)
        /go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:146 +0x458
net/http.HandlerFunc.ServeHTTP(0xc4204d0060, 0xe27860, 0xc42013e000, 0xc420156500)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201e0000, 0xe27860, 0xc42013e000, 0xc420156500)
        /go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:128 +0x203
github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.ProxyHeaders.func1(0xe27860, 0xc42013e000, 0xc420156500)
        /go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x117
net/http.HandlerFunc.ServeHTTP(0xc4204d00a0, 0xe27860, 0xc42013e000, 0xc420156500)
        /usr/local/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc4200b4680, 0xe27860, 0xc42013e000, 0xc420156500)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4202dc000, 0xe28220, 0xc4201a6700)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x27b
```

Sample of the JSON graphite-web returned:
` {\"datapoints\": [[352784.0, 1532365570], [352786.0, 1532365580], [352796.0, 1532365590], [352801.0, 1532365600], [352806.0, 1532365610], [352810.0, 1532365620], [352815.0, 1532365630], [352821.0, 1532365640], [352830.0, 1532365650], [352833.0, 1532365660], [352835.0, 1532365670], [352839.0, 1532365680], [352844.0, 1532365690], [352846.0, 1532365700], [352854.0, 1532365710], [352860.0, 1532365720], [352868.0, 1532365730], [352874.0, 1532365740], [352878.0, 1532365750], [352884.0, 1532365760], [352890.0, 1532365770], [352899.0, 1532365780], [352912.0, 1532365790], [352921.0, 1532365800], [352924.0, 1532365810], [352931.0, 1532365820], [352935.0, 1532365830], [352939.0, 1532365840], [352946.0, 1532365850], [352952.0, 1532365860], [352956.0, 1532365870], [352960.0, 1532365880], [352967.0, 1532365890], [352974.0, 1532365900], [352982.0, 1532365910], [352986.0, 1532365920], [352991.0, 1532365930], [352997.0, 1532365940], [353000.0, 1532365950], [353006.0, 1532365960], [353013.0, 1532365970], [353019.0, 1532365980], [353032.0, 1532365990], [353036.0, 1532366000], [353039.0, 1532366010], [353042.0, 1532366020], [353047.0, 1532366030], [353052.0, 1532366040], [353057.0, 1532366050], [353063.0, 1532366060], [353067.0, 1532366070], [353072.0, 1532366080], [353074.0, 1532366090], [353077.0, 1532366100], [353079.0, 1532366110], [353084.0, 1532366120], [353086.0, 1532366130], [353090.0, 1532366140], [353100.0, 1532366150], [353107.0, 1532366160], [353112.0, 1532366170], [353119.0, 1532366180], [353125.0, 1532366190], [353129.0, 1532366200], [353135.0, 1532366210], [353139.0, 1532366220], [353146.0, 1532366230], [353155.0, 1532366240], [353158.0, 1532366250], [353166.0, 1532366260], [353170.0, 1532366270], [353175.0, 1532366280], [353180.0, 1532366290], [353182.0, 1532366300], [353189.0, 1532366310], [353191.0, 1532366320], [353193.0, 1532366330], [353200.0, 1532366340], [353206.0, 1532366350], [353209.0, 1532366360], [353213.0, 1532366370], [353223.0, 1532366380], [353229.0, 1532366390], [353237.0, 1532366400], [353245.0, 1532366410], [353271.0, 1532366420], [353302.0, 1532366430], [353308.0, 1532366440], [353311.0, 1532366450], [353315.0, 1532366460]], \"target\": \"keepLastValue(**some_metric_path**)\", \"tags\": {\"name\": \"**some_metric_path**\"}}]"}`

When KeepLastValue not proxied:
`"have_non_fatal_errors":true, reason":"bad type`

**Comment by Civil** [comment]
If you are still interested in trying this out, could you test the current master and confirm if it's still happens?

**Comment by Civil** [comment]
Panic when keepLastValue is proxied should be fixed by https://github.com/go-graphite/carbonapi/commit/84119c5da7053b763b89ab9d8194d1f8f4ea0c40

So could you please try again and see if it's still an issue with master.

Also it would be nice to have full error when KeepLastValue is not proxied and also to see at least some example of metric path (e.x. if it contains utf-8 characters, if it is - then you need to manually enable that charset support: https://github.com/go-graphite/carbonapi/blob/master/doc/configuration.md#unicoderangetables)


Please reopen if it still happens.
