### ISSUE TITLE
What are the goals of the API/Zipper merge?

### ISSUE THREAD

**Issue by gunnihinn** [go-graphite/carbonapi#359]
I've heard bits and pieces of the motivation behind merging carbonapi and carbonzipper, but if anyone here has a more complete picture of what problems we're trying to solve here I'd appreciate some education. Otherwise it's not easy to know how it's actually going.

**Comment by Civil** [comment]
As usual it was a couple of reasons:
1. It was an attempt to workaround extra serialization-deserialization overhead for heavy queries. As zipper will have 5 copies of a query (4 to merge, one result) + api will have a copy of the data. So by merging we'll get rid of 2 copies of data (+ some extra mem and cpu to serialize, gzip, ungzip, deserialize). That was the main reason behind merge.
2. With the increasing complexity of queries and features we wanted to have it makes more sense to have zipper and api in a single binary, as it will allow more tight communication between them. It was before we wanted to move to gRPC though.

**Comment by gunnihinn** [comment]
> 1. It was an attempt to workaround extra serialization-deserialization overhead for heavy queries. As zipper will have 5 copies of a query (4 to merge, one result) + api will have a copy of the data. So by merging we'll get rid of 2 copies of data (+ some extra mem and cpu to serialize, gzip, ungzip, deserialize). That was the main reason behind merge.

Do you know if we had measurements or profiling data that pointed to
this overhead being a major bottleneck?

> 2. With the increasing complexity of queries and features we wanted to have it makes more sense to have zipper and api in a single binary, as it will allow more tight communication between them. It was before we wanted to move to gRPC though.

Does having gRPC move the bar here either way? I've never used it, so
I'm mostly asking out of ignorance.

For tighter communication, do you remember some of the things you were
thinking of that would be profitable? I can think of a couple (try to
move some math down the funnel, for example) but they're nontrivial to
pull off.

Thanks for taking the time to reply. Knowing this makes it easier to
define what moving towards success looks like.

**Comment by stepashka** [comment]
One of the things that @azhiltsov mentioned at one point is that this change allows frontends(api+zipper) to be more resilient to individual storage cluster (go-carbon) failures. I'm not sure if this was motivation or a nice side effect? :) Was that planned, intended?

**Comment by Civil** [comment]
> Do you know if we had measurements or profiling data that pointed to
this overhead being a major bottleneck?

I don't know if you have those. But you can do a thought experiment. You store 6 vs 4 copies of data in memory (remember that background phase of GC is not instant), that gives you 33% saving in memory footprint of the zipper+api combination. That doesn't count gziped data, etc.

> Does having gRPC move the bar here either way? I've never used it, so
I'm mostly asking out of ignorance.

gRPC is just a RPC on top of HTTP/2 and that uses Protobuf for serialisation. So it have all pros and cons of any other RPC approach. gRPC have it's overhead in terms of processing, as everything have, so it's ok do hundreds and thousands of RPC calls per second, but if each CarbonAPI query will require tens thousands calls - it will be of course too much (overhead will be visible).

> For tighter communication, do you remember some of the things you were
thinking of that would be profitable? I can think of a couple (try to
move some math down the funnel, for example) but they're nontrivial to
pull off.

I'm sorry, but I don't remember the full list. Here's what I remember:
- Much easier to implement all the fancy stuff like passing down functions (you've mentioned that already) and stuff like stampede prevention.
- As a next big thing I wanted to migrate to Streaming gRPC between carbonapi and go-carbon - that's actually a really major rework and all the stuff you saw (splitting functions, merging zipper, new protocol) was all a preparation work for that. So the idea was to stream data from the backends, zip them on demand (whenever function actually requests next portion of data) and start applying math (one that's safe to do) as soon as possible. Having extra service between API and Zipper of course possible but it will make things much more complicated.

> One of the things that @azhiltsov mentioned at one point is that this change allows frontends(api+zipper) to be more resilient to individual storage cluster (go-carbon) failures. I'm not sure if this was motivation or a nice side effect? :) Was that planned, intended?

Actually he might remember something that I already forgot :) I even think he might still had a photo of a whiteboard where we with Damian put all the plans we got.

As about side effect - that wasn't planned, and if it is a thing, it might be a result of major rework of a zipper, not a result of a merge.
