### ISSUE TITLE
very long log line

### ISSUE THREAD

**Issue by matthew-hollick** [go-graphite/carbonapi#362]
Hi,
We have recently implemented carbonapi. Occasionally we have seen log entries like:

`{"level":"ERROR","timestamp":"2018-09-17T07:39:14.565Z","logger":"render","message":"render error occurred while fetching data","errors":[{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No responses fetched from upstream"},{"error":"No metrics in the response"},{"error":"No responses fetched from upstream"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No metrics in the response"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No metrics in the response"},{"error":"No responses fetched from upstream"},{"error":"No responses fetched from upstream"},{"error":"No metrics in the response"}`
where the error message repeats for something like 12MB, all on one line.

we are running 0.10.0.1 from the apt repo on ubuntu 16.04
upstream is go-carbon.
we have not deviated much from the example configuration.
not quite sure what other information to provide.

**Comment by Civil** [comment]
Since then there was a new release - 0.12.0.

This issue should be fixed there.

However overall it means exactly what it says - that there were no valid response from backends.
