### ISSUE TITLE
Latest github release not available on packagecloud.io

### ISSUE THREAD

**Issue by matthew-hollick** [go-graphite/carbonapi#363]
Hi,

We are really loving carbonapi. The simplicity of configuration/deployment compared to graphite-web make it a worthwhile change even before the performance is considered.

I've noticed that the latest release on github is 0.11.0 where as the latest package available on packagecloud.io is 0.10.1.
Is 0.11.0 not ready for live deployments yet?

Cheers,

Matthew.

**Comment by gunnihinn** [comment]
> #361 is the reason

No, 0.11.0 should be fine. What we're running in production is based off that.

**Comment by ivanich** [comment]
Autobuilds gets created with wrong package name, carbonzipper instead of carbonapi.
https://packagecloud.io/go-graphite/autobuilds

**Comment by Hipska** [comment]
Since 0.11.0 is out for quite some time, would it not be a good idea to push that package to package cloud as well? As far as I can see, that push has nothing to do how much time you can/will spend for development.

**Comment by Civil** [comment]
https://packagecloud.io/go-graphite/autobuilds now contains autobuilds again (current master)
https://packagecloud.io/go-graphite/stable received 0.11.1

However I've currently dropped building packages for Ubuntu 14.04 and Debian Jessie.

Also for CentOS Versioning slightly changed.
