### ISSUE TITLE
-envprefix should omit trailing '_'

### ISSUE THREAD

**Issue by kkopachev** [go-graphite/carbonapi#373]
Despite the fact that prefix is defaulted to `CARBONAPI_`, in order to actually use env variables one have to pass `CARBONAPI__LISTEN` (note double `_`) to make it work.
Additionally, I figured there is no way to request empty prefix, as it defaults back to `CARBONAPI_` which makes this check https://github.com/go-graphite/carbonapi/blob/master/cmd/carbonapi/main.go#L706 useless

**Comment by Civil** [comment]
I've added a special prefix `(empty)` that will be treated as empty prefix.
