### ISSUE TITLE
Any documentation or Installation instructions for carbonapi?

### ISSUE THREAD

**Issue by cjagus** [go-graphite/carbonapi#380]

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonapi/blob/master/cmd/carbonapi/README.md

I'll add a link to the main readme file.

**Comment by Civil** [comment]
Now the instructions are moved to the main readme. I hope that solves this issue, however feel free to reopen it if it's still not solved. But please provide more details on what problems you had with the docs?

P.S. for a broken package autobuilds there is a separate issue.
