### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by blysik** [go-graphite/carbonapi#382]
It's been a while since we had a new release. Time for a new version?  Seems like a lot of fixes since 0.11.  What's the plan?  Thanks.

**Comment by Civil** [comment]
Well, I'm still taking a break from the active development and only merging the PRs.

However I plan to start actively working (less active than it was 1y ago though) on the project this month.

As of cutting new release - I think it would be worth to cut it when the current -rc would seem to be stable. At this moment I'm worried about:
#361, #363 and #379 and would call them a release blockers. First one is hard for me to reproduce at this moment, as I don't have access to a large scale environment anymore and I can only rely on the information provided in the issue by other users.

However I'd like to approach #369 but after fixing those 3 I've mentioned.

**Comment by Civil** [comment]
So, as of know, tag support was added not so long ago. I'll try to approach #361 and if I'll be able to find the issue and fix it - I'll cut a new release. However I think I'll call it 0.12, instead of 1.0.

Still the plan is to do that before spring, but actually it might happen at some point in February.

**Comment by aptituz** [comment]
Any chance for a bugfix release of 0.11 with just the fix for #379?

**Comment by Hipska** [comment]
Hi @Civil, any update on development commitment? It is spring and I don't see a new release yet. Are you still planning to make a new release?

**Comment by Civil** [comment]
Answering those questions - I indeed have plan to do both.

I'll try to cut a bugfix release for 0.11 with just backport of #379 

As about a new release - I'll tag something like rc.0 after I finish work on: #391 and #390

Sorry that it takes longer than I promised.

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonapi/releases/tag/0.11.1 - 0.11 + fix for pickle
and
https://github.com/go-graphite/carbonapi/releases/tag/0.12.0-rc.0 - current master.

Howver currently package builder is broken and I'll need to find some time to fix it and to build packages for both.

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonapi/releases/tag/0.12.0
