### ISSUE TITLE
Panic in response

### ISSUE THREAD

**Issue by proffust** [go-graphite/carbonapi#387]
During a query with dots in tag values with multiple tags, I get a panic in the response. With the same query but without dots in tag values, the answer is correct.
Log failed request
https://pastebin.com/SLY2mfWX
Log success request
https://pastebin.com/g5BuTTta

**Comment by proffust** [comment]
any updates?

**Comment by Civil** [comment]
So far can't reproduce with current master.

**Comment by Civil** [comment]
Should be fixed by:
https://github.com/go-graphite/carbonapi/commit/5a4fa2112923dd4c5d1a07164809a9da40dc0524
