### ISSUE TITLE
aliasByTags is broken ?

### ISSUE THREAD

**Issue by msaf1980** [go-graphite/carbonapi#390]
Hi.

As I undestand, aliasByTags is broken

For example query 
seriesByTag('name=DevOps.test.test_tag')|aliasByTags("server","name")

> github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler() ./cmd/carbonapi/http/render_handler.go:191 (PC: 0xe44b61)
(dlv) p exp
github.com/go-graphite/carbonapi/pkg/parser.Expr(*github.com/go-graphite/carbonapi/pkg/parser.expr) *{
	target: "aliasByTags",
	etype: EtFunc,
	val: 0,
	valStr: "",
	args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 3, cap: 4, [
		*(*github.com/go-graphite/carbonapi/pkg/parser.expr)(0xc000176600),
		*(*github.com/go-graphite/carbonapi/pkg/parser.expr)(0xc00025df80),
		*(*github.com/go-graphite/carbonapi/pkg/parser.expr)(0xc00047c000),
	],
	namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
	argString: "seriesByTag('name=DevOps.test.test_tag'),server,name",}
(dlv) p exp.args
[]*github.com/go-graphite/carbonapi/pkg/parser.expr len: 3, cap: 4, [
	*{
		target: "seriesByTag('name=DevOps.test.test_tag')",
		etype: EtName,
		val: 0,
		valStr: "",
		args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 0, cap: 0, nil,
		namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
		argString: "",},
	*{
		target: "server",
		etype: EtName,
		val: 0,
		valStr: "",
		args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 0, cap: 0, nil,
		namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
		argString: "",},
	*{
		target: "name",
		etype: EtName,
		val: 0,
		valStr: "",
		args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 0, cap: 0, nil,
		namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
		argString: "",},
]

Parsed arguments for aliasByTags has type EtName

But in expr.GetNodeOrTagArgs(n) (see pkg/parser/parser.go) we want Int or String 

>354         nodeTag.Value, err = e.GetIntArg(i)                                                                   
355         if err != nil {                                                                                       
356             // Try to parse it as String                                                                      
357             nodeTag.Value, err = e.GetStringArg(i) 

As result, got 'bad type' error.

> github.com/go-graphite/carbonapi/expr/functions/aliasByTags.(*aliasByTags).Do() ./expr/functions/aliasByTags/function.go:51 (PC: 0xd65a6d)
    46:		if err != nil {
    47:			return nil, err
    48:		}
    49:	
    50:		tags, err := e.GetNodeOrTagArgs(1)
=>  51:		if err != nil {
    52:			return nil, err
    53:		}
    54:	
    55:		var results []*types.MetricData
    56:	
(dlv) p tags
[]github.com/go-graphite/carbonapi/pkg/parser.NodeOrTag len: 0, cap: 0, nil
(dlv) p err
error(*errors.errorString) *{
	s: "bad type",}

What's going wrong ? Need some changes in parseExprWithoutPipe for this case ? Or expr.GetNodeOrTagArgs for accept EtName type ?

**Comment by Civil** [comment]
I would actually suspect that it's the piped syntax misbehaves. Could you please check, that the query without piped syntax works?

E.x.
aliasByTags(seriesByTag('name=DevOps.test.test_tag'), "server","name")

**Comment by msaf1980** [comment]
No difference. Parsing result from ParseExpr is equal to piped expression.

**Comment by Civil** [comment]
Sorry, I cannot reproduce:
```
> github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler() ./http/render_handler.go:191 (hits goroutine(44):1 total:1) (PC: 0xe3eb53)
   186:                 targetIdx++
   187:
   188:                 exp, e, err := parser.ParseExpr(target)
   189:
   190:                 // if expression cannot be parsed return error
=> 191:                 if err != nil || e != "" {
   192:                         msg := buildParseErrorString(target, e, err)
   193:                         setError(w, accessLogDetails, msg, http.StatusBadRequest)
   194:                         logAsError = true
   195:                         return
   196:                 }
(dlv) p exp
github.com/go-graphite/carbonapi/pkg/parser.Expr(*github.com/go-graphite/carbonapi/pkg/parser.expr) *{
        target: "aliasByTags",
        etype: EtFunc (1),
        val: 0,
        valStr: "",
        args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 3, cap: 4, [
                *(*"github.com/go-graphite/carbonapi/pkg/parser.expr")(0xc00015cf00),
                *(*"github.com/go-graphite/carbonapi/pkg/parser.expr")(0xc00015cfc0),
                *(*"github.com/go-graphite/carbonapi/pkg/parser.expr")(0xc00015d020),
        ],
        namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
        argString: "seriesByTag('cpu=cpu-total','__name__=cpu.usage_user'),'os','cpu...+1 more",}
(dlv) p exp.args
[]*github.com/go-graphite/carbonapi/pkg/parser.expr len: 3, cap: 4, [
        *{
                target: "seriesByTag('cpu=cpu-total','__name__=cpu.usage_user')",
                etype: EtName (0),
                val: 0,
                valStr: "",
                args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 0, cap: 0, nil,
                namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
                argString: "",},
        *{
                target: "",
                etype: EtString (3),
                val: 0,
                valStr: "os",
                args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 0, cap: 0, nil,
                namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
                argString: "",},
        *{
                target: "",
                etype: EtString (3),
                val: 0,
                valStr: "cpu",
                args: []*github.com/go-graphite/carbonapi/pkg/parser.expr len: 0, cap: 0, nil,
                namedArgs: map[string]*github.com/go-graphite/carbonapi/pkg/parser.expr nil,
                argString: "",},
]
```

However I think I know what's going there.

If I do the request from Command Line, e.x.:
```
$ wget -q -O- "http://localhost:8081/render?from=-5m&target=seriesByTag('name=DevOps.test.test_tag')|aliasByTags("server","name")&format=json" | jq .; echo
```

I indeed have the same behavior as yours. But this is due to the fact that because I've used same type of quotes (`"`) inside the query and to pass argument to wget, the actual URL that got passed to carbonapi was:
```
/render?from=-5m&target=seriesByTag('name=DevOps.test.test_tag')|aliasByTags(server,name)&format=json
```

And therefore it was parsed as EtName, which is technically correct.

**Comment by Civil** [comment]
If this issue still happens in current release (and taking into account my last comment about quotes), please reopen.
