### ISSUE TITLE
Return 500 if no backends are reachable

### ISSUE THREAD

**Issue by blind-oracle** [go-graphite/carbonapi#397]
Currently if the storage backend (e.g. `graphite-clickhouse`) is down, `carbonapi` returns 200 OK and empty response.

This makes it hard to actually distinguish fatal errors and when there are no metrics found e.g. when doing health checks from proxy.

My proposal is to return 500 if all backends return 500 or not reachable. And not treat backend's error 404 as fatal (it is considered fatal now), but instead treat it as "no metrics found".

@Civil I can try to do a PR for this if you agree or maybe you want to look into it yourself

Thanks.

**Comment by azhiltsov** [comment]
You can consider to patch it accordingly to this PR 
https://github.com/bookingcom/carbonapi/pull/143

**Comment by Civil** [comment]
Depends on your availability. I usually have some time during Friday-Sunday to work on this project. Sometimes I might have some time during weekdays, but that's not guaranteed.

@azhiltsov thx, I'll evaluate if taking into account difference between our codebases it's worth to port your series of patches or they'll need to be re implemented. Actually that's a good suggestion as well for @blind-oracle  - maybe see if it'll be straightforward enough to port Booking.com's patches.

**Comment by Civil** [comment]
I would say that overall getting rid of zipper/errors in favor of golang.org/x/xerrors and having several wrappers would be the best idea overall.

E.x. have custom structs for different type of errors, from broadcast group return `[]error` and have helper functions that will check if it's "only" backend failures or "404s" would be something that I'd like to move to.

And in that case zipper could also return typed error (`xerror.Errorf("no metrics found", errorsFromBroadcast)` or `xerrors.Errorf("all backends are down", errorsFromBroadcast)`) or something like that.

Then it would be rather easy and clean to check what exactly it is on a carbonapi side and to choose a return code based on that.

Actually it also can be used to update a path cache if we'd like to handle "no metrics found" there.

**Comment by blind-oracle** [comment]
@Civil 
I've worked around the problem for now by introducing `HAProxy` between `carbonapi` and `graphite-clickhouse`. Will try to get back to this problem a little later when I'll have time.

> I would say that overall getting rid of zipper/errors in favor of golang.org/x/xerrors and having several wrappers would be the best idea overall.

If I'm reading it's docs correctly almost all of it's functionality is merged into go 1.13 so we shouldn't start using x package for new development I guess. I would wait for august to see what it brings. It will break backwards compatibility with earlier versions, but in case of Go it does not matter much I guess.

**Comment by Civil** [comment]
Well, migration from xerrors to default errors package should be straightforward so I do not really see any issues with using xerrors for now.

**Comment by Civil** [comment]
Didn't have enough time this weekend to work on this. Maybe will do during next week or so.

**Comment by Civil** [comment]
Also carbonapi should try to gather all responses if some of them returned 5xx or 404 (AFAIR currently it will try to fetch responses until it receive first 500 from the backend).

And another note for myself - make error logs less verbose - there is no need to write anything if we only saw one 404. And for 5xx it's worth mentioning only on carbonapi level - that results might be incomplete.

And idea for the future - it might be worth checking if it would be possible to implement something like `&loglevel=debug` URL Parameter to temporary increase loglevel to debug but only for this query.

**Comment by Civil** [comment]
I've created a separate branch where I did some work on rethinking error handling across all packages:
https://github.com/go-graphite/carbonapi/tree/zipper_improve_errorhandling

Feel free to test.

It works on some basic test queries and in test cases, however I haven't performed extended tests on it yet.

**Comment by Civil** [comment]
It should be fixed in current master.
