### ISSUE TITLE
In some cases request for metric will be sent twice

### ISSUE THREAD

**Issue by Civil** [go-graphite/carbonapi#401]
Example query:
```
maxSeires(m, m)
```

Will result in two queries for metric 'm'.

**Comment by dgryski** [comment]
We don't perform request collapsing. The `singleflight` package might help .

**Comment by Civil** [comment]
Well, it's sort of regression compared with carbonapi 0.11 or earlier (where zipper was a separate process) as currently requests are combined together and passed as:
```
/render/?target=m&target=m
```

But before it would've result in 2 requests for:
```
/render/?target=m
```

And the second one likely would be a cache hit.

**Comment by Civil** [comment]
This only happens with cache=null
