### ISSUE TITLE
Problem with escaping ‘.’ in grafana variables

### ISSUE THREAD

**Issue by ifireice** [go-graphite/carbonapi#402]
Hi, I have the following behavior:

0. I am using Clickhouse-Graphite pipeline for metrics with tags. Render metrics with Carbonapi (Grafana -> Carbonapi -> Graphite-clickhouse -> Clickhouse) 
Versions Clickhouse 19.9.2.4, Carbonapi 0.12.0, Graphite-clickhouse 0.11.1 

1. I create variable in grafana `service = tag_value(services)`.
Variable contains values different types: with dot and without dot. Example,`"unknown", "istio-telemetry.istio-system.svc.cluster.local"`

2. I make requests in Grafana
    `service = istio-telemetry.istio-system.svc.cluster.local'`

`seriesByTag('name=istio_requests_total','destination_service=~${service:regex}') `
  returns NoData

 `seriesByTag('name=istio_requests_total', 'destination_service=~istio-telemetry.istio-system.svc.cluster.local')`
 returns data points

If I look closely Grafana requests then I see next cases:
1. I am using variable when contain dot in value. 
The sequence will be as follows:

- Grafana escapes point with help '\' and send request to Carbonapi with next content 
`seriesByTag('name=istio_requests_total', 'destination_service=~istio-telemetry\.istio-system\.svc\.cluster\.local')`

-  Carbonap escapes '\' and send request to Graphite-clickhouse. Request contains already 2 '\' instead of 1
 `{"type": "broadcastGroup", "groupName": "root", "type": "fetch", "request": ["seriesByTag('name=istio_requests_total', 'destination_service=~istio-telemetry\\.istio-system\\.svc\\.cluster\\.local')"], "backend_name": "clickhouse-cluster", "max_connections": 0}`

- Request comes in Graphite-clickhouse and ' \' once again escapes. Request already looks so 
`[query] query {"query": "SELECT Path FROM graphite_tagged  WHERE ((Date >='2019-07-09' AND Date <= '2019-07-09')) AND ((Tag1='__name__=istio_requests_total') AND (arrayExists((x) -> x='reporter=source', Tags)) AND (arrayExists((x) -> (x LIKE 'destination_service=app\\\\%') AND (match(x, 'destination_service=app\\\\.service-foo\\\\.svc\\\\.cluster\\\\.local')), Tags))) GROUP BY Path", "request_id": "93e4dff55b84161383fcc6636fa00644", "time": 0.015662523}`

- Clickhouse says when he hasn't data points on this request and return empty result. 
However, if in request contant once '\' which escape dot when Clickhouse , interprets request "correctly" and returns expect data points.  Example, `...'destination_service=app\.service-foo\.svc\.cluster\.local'... `

2. If I create request which contanins same couple tags=value, but value I chouse from the list of acceptable variable (proposed Grafana) then 

- Grafana doesn't escape dot and send request   `seriesByTag('name=istio_requests_total', 'destination_service=~back.service-foo.svc.cluster.local')`

- Carbonapi `{"type": "broadcastGroup", "groupName": "root", "type": "fetch", "request": ["seriesByTag('name=istio_requests_total', 'destination_service=~istio-telemetry.istio-system.svc.cluster.local')"], "backend_name": "clickhouse-cluster"}`

- Graphite-clickhouse  `query {"query": "SELECT Path FROM graphite_tagged  WHERE ((Date >='2019-07-07' AND Date <= '2019-07-09')) AND ((Tag1='__name__=istio_requests_total') AND (arrayExists((x) -> (x LIKE 'destination_service=istio-telemetry%') AND (match(x, 'destination_service=istio-telemetry.istio-system.svc.cluster.local')), Tags))) GROUP BY Path", "request_id": "4bb7a4bbd2bbf04a2d8f6c10e01c4098", "time": 0.074417618}`

-  Clickhouse returnes expect data points and  graph draws =)

Is It normal behavior or is It a bug? 
How can I draw a graph with a variable that contains a dot in the value?

**Comment by Civil** [comment]
Actually that sounds like a bug and that carbonapi tries to escape '\' when it shouldn't. But I'll have a closer look (won't promise that it'll happen today though)

**Comment by Civil** [comment]
I've checked that behavior, and there is no extra escaping happens during those queries.

Escaping happens only when logging library prints the corresponding log lines.

You can check graphite-clickhouse's messages:
```
[2019-07-09T23:31:17.799+0200] INFO access {"request_id": "f8c93142f2b99f3b44ab5c4269e5c6a9", "time": 0.038552592, "method": "GET", "url": "/render/?format=protobuf&from=1562706977&target=seriesByTag%28%27cpu%3Dcpu-total%27%2C+%27host%3D~Vladimirs-MacBook-Pro%5C.local%27%29&until=1562707877", "peer": "127.0.0.1:50542", "status": 404}
[2019-07-09T23:31:17.802+0200] INFO access {"request_id": "b1acb5dc2a1523e6ba4f4bc31dc83855", "time": 0.025891276, "method": "GET", "url": "/render/?format=pickle&local=1&noCache=1&from=1562706977&until=1562707877&target=seriesByTag%28%27cpu%3Dcpu-total%27%2C+%27host%3D%7EVladimirs-MacBook-Pro%5C.local%27%29&now=1562707877", "peer": "127.0.0.1:50546", "status": 200}
```

If you'll pass those requests through URL Decode you'll see that they are exactly the same and contains only one '\'.

To be sure you can double check that by using tcpdump:
for graphite-web it will be:
```
GET /render/?format=pickle&local=1&noCache=1&from=1562706977&until=1562707877&target=seriesByTag%28%27cpu%3Dcpu-total%27%2C+%27host%3D%7EVladimirs-MacBook-Pro%5C.local%27%29&now=1562707877 HTTP/1.1
Host: 127.0.0.1:9090
Accept-Encoding: identity
```

for carbonapi it will be:
```
GET /render/?format=protobuf&from=1562706977&target=seriesByTag%28%27cpu%3Dcpu-total%27%2C+%27host%3D~Vladimirs-MacBook-Pro%5C.local%27%29&until=1562707877 HTTP/1.1
Host: 127.0.0.1:9090
User-Agent: Go-http-client/1.1
Accept: application/x-protobuf
X-Ctx-Carbonapi-Uuid: eee32bbd-135a-491d-b539-dee4747b329f
X-Ctx-Carbonzipper-Uuid: eee32bbd-135a-491d-b539-dee4747b329f
Accept-Encoding: gzip
```

However if you'll look closer to graphite-clickhouse logs:
```
[2019-07-09T23:31:17.799+0200] INFO [query] query {"query": "SELECT Path FROM graphite_tagged  WHERE ((Date >='2019-07-09' AND Date <= '2019-07-09')) AND ((Tag1='cpu=cpu-total') AND (arrayExists((x) -> (x LIKE 'host=Vladimirs-MacBook-Pro\\\\%') AND (match(x, 'host=Vladimirs-MacBook-Pro\\\\.local')), Tags))) GROUP BY Path", "request_id": "f8c93142f2b99f3b44ab5c4269e5c6a9", "time": 0.038464092}
```

So graphite-clickhouse execute following query (extra escape removed):
```
SELECT Path FROM graphite_tagged  WHERE ((Date >='2019-07-09' AND Date <= '2019-07-09')) AND ((Tag1='cpu=cpu-total') AND (arrayExists((x) -> (x LIKE 'host=Vladimirs-MacBook-Pro\\%') AND (match(x, 'host=Vladimirs-MacBook-Pro\\.local')), Tags))) GROUP BY Path
```

You can notice extra `\\` in `LIKE 'host=Vladimirs-MacBook-Pro\\%'`.

If you manually remove `\\` from there, your query would run just fine.

So the issue is on graphite-clickhouse side and it was fixed by it's author here: https://github.com/lomik/graphite-clickhouse/commit/46adf56a1b6ef6fb1a9848311f75837deaef32c2

**Comment by Civil** [comment]
P.S. Also I've just tagged carbonapi 0.12.2 and I would recommend to use this version as I would consider it current stable.

**Comment by ifireice** [comment]
Guys, you are awesome, thank you for help =)
