### ISSUE TITLE
Bad rendering using fallback graphiteWeb 

### ISSUE THREAD

**Issue by sylvain-beugin** [go-graphite/carbonapi#403]
With latest version 0.12.2 ,when using fallback to graphiteWeb, carbonapi do the request to graphiteWeb correctly (even with maxDatapoint option) but return bad points in response (value is the same as date)

[{"target":"smartSummarize(server.collectd.cpu-0.cpu-idle, \"10min\", \"max\")","datapoints":[[**1562584320**,**1562584320**],[1562584920,1562584920],[1562585520,1562585520],....]}]

I have patched expr/functions/graphiteWeb/function.go  and it seems to correct this bug:

 for i, v := range m.Datapoints {
                        **pbResp.Values[i] = v[0]**
                }

I use graphite web 1.1.4 and value is always in first element:

 curl "http://localhost/graphite/render/?format=json&from=1562733833&target=smartSummarize%28mservercollectd.cpu-0.cpu-idle%2C+%2710min%27%2C+%27max%27%29&until=1562755433"

[{"datapoints": [[**99.033587**, **1562733840**], [98.965809, 1562734440],

**Comment by Civil** [comment]
Yeah, that might be the case. I thought I've corrected that issue.

Could you send a PR to fix that?

**Comment by Civil** [comment]
Merged it. Thanks.
P.S. If you specify in the commit `Fixes #403` github will automatically close the issue :)
