### ISSUE TITLE
Question: Will Carbonapi work with Go-Carbon, mariadb, and Whisper alone?

### ISSUE THREAD

**Issue by Bain-Inc** [go-graphite/carbonapi#406]
Hello-
I want to decommission graphite-web and run the Go products Go-Carbon (with carbonserver enabled), and carbonapi along with mariadb.  Can this be done without Graphite-web?  Can carbonserver and carbonapi replace the Apache stack as well? 

Additionally, is it pretty straightforward to setup SSL certs with carbonapi or carbonserver? 

Thanks,
Mike

**Comment by Civil** [comment]
1. Carbonapi doesn't need database to run. It only implement tagdb functionality and rely on underlying storage to be able to store tags. Currently tags support is tested with graphite-clickhouse project, as to my knowledge there is no support for tags in carbonserver (in this project you can find a fork of go-carbon with some initial work on tag support for carbonserver but it's a bit old and untested, I wouldn't recommend to use it in production)
2. Currently there is no ssl support in Carbonapi. (It's easy to implement, but no one asked for that). To my knowledge there is no ssl support in go-carbon's carbonserver as well.

**Comment by Bain-Inc** [comment]
Thank you.  Is this type of stack then possible:  whisper-> carbonapi->carbonserver->Grafana.  
I have a great need to completely remove Graphite-web and simplify the process.

Thanks!
Mike

**Comment by Civil** [comment]
it Should be:
Whisper -> go-carbon (carbonserver) -> carbonapi -> grafana

In this setup, Carbonserver will read whisper files and serve them to carbonapi. And carbonapi can talk with grafana.

**Comment by Bain-Inc** [comment]
Thanks much!
