### ISSUE TITLE
aggregations support in groupByTags is not complete

### ISSUE THREAD

**Issue by msaf1980** [go-graphite/carbonapi#410]
average, median, diff, stddev, range, multiply - not relized as described in https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.aggregate

For average fix in https://github.com/go-graphite/carbonapi/pull/409

For median I have fix with copy-past of percentileOfSeries. But may be a better solution ?

**Comment by Civil** [comment]
Actually I think it would be better to unify those with https://github.com/go-graphite/carbonapi/blob/master/expr/functions/aggregate/function.go which supports all those types of aggregations (and merge current average, etc with the 'aggregate' if required).

**Comment by Civil** [comment]
Last commit should now support everything that 'aggregate' can do.
