### ISSUE TITLE
missing metric on 1 server  make the entire broadcast group failed

### ISSUE THREAD

**Issue by sylvain-beugin** [go-graphite/carbonapi#415]
Hi,

Here is my setup:
- carbonapi request 2  backends (stb01 and stb02)
- version: carbonapi 12.3-1 or 12.5-1  / lomik go-carbon 0.14.0
- all metrics are replicated across the 2 backends 
- BUT to test failover , i remove intentionaly a metric from stb02 : haggar.agent.1.metrics.10 

=> zipper merge process failed and nothing is returned ... 

see special log that indicate that zipper has no response (but in fact he got one valid response from stb01)

2019-08-19T18:31:32.720+0200	DEBUG	zipper	failed to get any response	{"type": "broadcastGroup", "groupName": "site1-render", "type": "fetch", "request": ["haggar.agent.1.metrics.10"]}

The strange thing is that merge process succeed if
- if using only one valid server stb01 (off course)
- using protocol carbonapi_v2_pb
- if putting stb01 and stb02 into 2 separate groups

Conf anf log attached:

[carbonapi_v2.log](https://github.com/go-graphite/carbonapi/files/3516849/carbonapi_v2.log)
[carbonapi_v3.log](https://github.com/go-graphite/carbonapi/files/3516850/carbonapi_v3.log)
[carbonapi_v3_different_groups.log](https://github.com/go-graphite/carbonapi/files/3516851/carbonapi_v3_different_groups.log)
[carbonapi_v3_only_stb01.log](https://github.com/go-graphite/carbonapi/files/3516852/carbonapi_v3_only_stb01.log)

Regards

**Comment by Civil** [comment]
Can you try building from https://github.com/go-graphite/carbonapi/tree/zipper_improve_errorhandling branch? I've just rebased it to current master.

It should have error handling logic redone and likely won't fail in the same situation.

**Comment by sylvain-beugin** [comment]
I have tried with this branch , the bug remains but we have a different behavior.

Now zipper seems to detect the valid response from valid server (stb01) 

_got some fetch responses ..._

But the final merged response isn't sent , only a HTTP 500 "Internal Server Error: empty or no response" even if it is a "non-fatal" error type

_had errors while fetching result	{"errors": "response contains non-fatal errors: response contains non-fatal errors: unexpected EOF"..._

If i understand the new wanted behavior:
- all backend response are 500 errors            => 500 error
- all backend  response  are 404 error           => 404 error (or  another code if configured)
- 1 request 200 OK and somes 500 or 404   =>  200 OK  ?

In fact 500 / 404 responses could lead to  an incomplete global response, but in this case it is nor a normal response, nor a fatal error , interpretation depends mainly on user context (merging metrics from different site , or merging data from replicated  servers).

I don't know if it is possible to notify grafana that response is incomplete like Elasticsearch/Kinana do. Anyway , to do this, carbonapi must be aware of replication strategy and it is not  the case.

Full log:
[carbonapi_v3_zipper_improve_errorhandling.log](https://github.com/go-graphite/carbonapi/files/3521770/carbonapi_v3_zipper_improve_errorhandling.log)

**Comment by sylvain-beugin** [comment]
Perhaps the best  approach to let user configure what to do in case of an unitary fatal response : continu or throw a 500 error:

 backends:
          -
            groupName    : "site1"
            groupFailStrategy : "continue"
            clusterReplicationFactor  : 1
            clusterFailStrategy          : "stop"
            servers
                - "http://server1:8090"
                - "http://server2:8090"

Actually groupFailStrategy seems to be "continu" and clusterFailStrategy   seems to be "stop"

**Comment by Civil** [comment]
I'll likely will have a look at it during the upcoming weekend.

Overall I like the idea of groupFailStratgey and clusterFailStrategy parameter, but I'll need to do some repro environment for that.

**Comment by Civil** [comment]
I've merged the PR that should fix it to the master. Could you please verify that?

For now I haven't implemented the Fail Strategy idea, but overall I like the idea and I'll likely will implement it in future. However I'm currently thinking that just one option "failStrategy" should be enough - if it's specified inside a broadcast group it will affect only group, but once specified on top level it seems that it would be equal to 'groupFailStrategy" you've mentioned.

**Comment by Civil** [comment]
This should be fixed in current master.
