### ISSUE TITLE
Option to return x axis data in multiple formats such as js timestamp

### ISSUE THREAD

**Issue by NucleaPeon** [go-graphite/carbonapi#418]
I'm trying to figure out a way to return graph data x timeseries values in a timestamp format that includes milliseconds for compatibility with d3.js/javascript.

I've been looking at the graphite-web documentation for solutions. I noticed that `dygraph`'s `format` option has the correct timestamp format whereas the others do not: https://graphite.readthedocs.io/en/latest/render_api.html#format. 

I've also looked at `scale()` and `group()` functions but I'm not sure if they are what I need. there are already existing scale() calls for the y axis data, I'm not quite sure how to reference the x axis data.

I am a bit new to graphite so I apologize if this is something obvious.
Much appreciated in advance. Let me know if I can provide more information.

**Comment by Civil** [comment]
Well, currently you are the first one who asked about dygraph output format, so no one actually bothered implementing that :)

It should be relatively easy, but would require implementing a new output format here: https://github.com/go-graphite/carbonapi/blob/master/cmd/carbonapi/http/render_handler.go#L314-L338

Basically what should be done is a new data structure should be defined, based on the dygraph format output from graphite-web and then a custom MarshalDygraph function should be created that would convert the current protobuf format to this new data structure.

I'm not sure when I'll get into doing this (I'd like to fix the current error handling process before and I didn't had enough time to finish it in last 2 weeks or so).

**Comment by NucleaPeon** [comment]
> Well, currently you are the first one who asked about dygraph output format, so no one actually bothered implementing that :)

That's funny :)

Though to be clear, my issue isn't that I want to use the dygraph format, just that it is the only example of a different timeseries format being returned:
```
{
  "labels" : [
    "Time",
    "entries"
  ],
  "data" : [
    [1468791890000, 0.0],
    [1468791900000, 0.0]
  ]
}
```
vs json
```
[{
  "target": "entries",
  "datapoints": [
    [1.0, 1311836008],
    [2.0, 1311836009],
    [3.0, 1311836010],
    [5.0, 1311836011],
    [6.0, 1311836012]
  ]
}]
```

I was hoping for an option along the lines of `&timeseriesFormat=` where you could specify the date format being returned, possibly utilizing the python datetime format specification (https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior). Although those docs have many good datetime formatting options, I'm not seeing a way to specify exactly what I'm looking for. Python returns a float with 6 decimals for microseconds but I want milliseconds and there's no exact directive for that. It would leave me with 3 additional decimal values so there wouldn't be a format I can use verbatim.

Currently I'm multiplying all json format x values by 1000 after we get the graph render response back from graphite/carbon, but I am hoping to avoid doing that. It is a workaround we've been using for a while.

**Comment by NucleaPeon** [comment]
I understand this may not be a feature you want to implement, as it may end up being cruft or undesired complexity with less usefulness than other features. Feel free to close it, this ticket is more or less to document how I wanted to use the software.

**Comment by Civil** [comment]
Please review latest commit to master.

I've added query parameter, called `timestampMultiplier` which accepts one of following values:
s - default, multiplier = 1
ms - milliseconds, multiply all timestamps by 1000
us - microseconds, multiply all timestamps by 1000000
ns - nanoseconds, multiply all timestamps by 1000000000

No extra checks implemented.

**Comment by Civil** [comment]
As there was no comments about that, I think that it's now solved.

Please reopen if you have any problems with current implementation or any other suggestions.
