### ISSUE TITLE
Weird inconsistent scaleToSeconds() behavior

### ISSUE THREAD

**Issue by reyjrar** [go-graphite/carbonapi#421]
I have a graph that shows a week of data and the same data `timeshift()`'d `7d` or `1w`, so `14d` of total data.  Now this particular metric rolls up from `1m` resolution to `5m` resolution at `14d`.  Both series have a `scaleToSeconds(1)` applied to get a per second hit count.  Graphs are being assembled in **Grafana**.

### What Happens?

With `graphite-web`, the data lines up as expected, the current week and previous week values are aligned as expected.

When I switched to using `cabonapi` the previous week values are now 1/5th the value I expect.  If I drop the display area to "Last 2 days" or even "Last 6 Days" `carbonapi` and `graphite-web` both draw the same lines.  It's only when I move the display window to **touch** the rollup boundary at the edge that things go pear-shaped.

### Weirder still

If I drop the `scaleToSeconds()` from the query, both `graphite-web` and `carbonapi` display the same lines.

**Comment by Hipska** [comment]
You might need the `perSecond` function I guess.

**Comment by Civil** [comment]
I think this behavior should be fixed in current master. Could you please confirm that it behaves as expected?

**Comment by reyjrar** [comment]
Apologies for the lag, I can confirm this is fixed.
