### ISSUE TITLE
groupByNodes should support tags as well

### ISSUE THREAD

**Issue by ddpolyakov** [go-graphite/carbonapi#430]
Hi there
Im using graphite + clickhouse + grafana stack. When Im trying to use groupByNodes function - Im having  "request failed" with "function=groupByNodes, err=bad type" reason. Using the same query with graphite-web is OK (except query time, huh). From graphite-clickhouse log I can see, that response is ok and it gives back points. Log is in attach. 

[test2.log](https://github.com/go-graphite/carbonapi/files/3797103/test2.log)

**Comment by Civil** [comment]
I somehow missed that in graphite-web they modified groupByNode/groupByNodes to support not only node number but also tags.

For now in carbonapi unfortunately if you should use groupByTags

**Comment by ddpolyakov** [comment]
Thanks for fast reply. groupByTags is working well.

**Comment by Civil** [comment]
I'll keep the issue open as it's about compatibility with graphite web and should be fixed eventually

**Comment by Civil** [comment]
I think that's fixed in current master since #507 was merged.

If that still doesn't work - please comment here and I'll reopen the issue

**Comment by Felixoid** [comment]
I guess it's related to #512 as well
