### ISSUE TITLE
Group returns no data if one of the metrics has no data

### ISSUE THREAD

**Issue by disorder** [go-graphite/carbonapi#434]
Hello,

I've come across compatibility issue with carbonapi related to `group()`.  When requesting graph for multiple series in one target it returns No Data instead of a graph with metrics which do have data.  I've made simplified target that demonstrates this: `target=group(sumSeries(metricA),sumSeries(metricB))` where one of the metrics was not created or has no data in the selected timeframe.

This is with carbonapi 0.12.6 installed from Debian package.

**Comment by Civil** [comment]
I'll try to create a test for that in near future (likely this week).

**Comment by Civil** [comment]
Could you please retest with current master, as there were numerous improvements to handling such cases?

**Comment by disorder** [comment]
This seems to be working now.  The issue seems to persist when any of the metrics have no data (#438).
