### ISSUE TITLE
Internal Server Error: empty or no response

### ISSUE THREAD

**Issue by disorder** [go-graphite/carbonapi#438]
Hello,

After upgrade from 0.12.6 while testing #435 fix I am seeing "Internal Server Error: empty or no response" when target metric does not exist.

0.12.6 returns "[{"target":"","datapoints":[],"tags":{}}]"
graphite-web returns "[]"

**Comment by disorder** [comment]
I tried to rebuild by running make and running the same render request as before - I'm getting HTTP 500 now instead of image or JSON, with this on page: `Internal Server Error: empty or no response`

**Comment by disorder** [comment]
I can't confirmed this ever worked, now the error is:
```
Internal Server Error (500) Details: all targets failed with mixed errrors; merged errs: (all metrics failed with mixed errrors; merged errs: (all requests failed with mixed errrors; merged errs: (Unknown content type '', ), ), )
```

**Comment by Civil** [comment]
Should be fixed in current master.
