### ISSUE TITLE
yum install no default config

### ISSUE THREAD

**Issue by purpurpur00** [go-graphite/carbonapi#447]
No folder /etc/carbonapi and defauld config at /etc/carbonapi/carbonapi.yaml after installing with 
`sudo yum install carbonapi`

So after `sudo service carbonapi start` we got error about this:

`FATAL        main        error reading config file        {"config_path": "/etc/carbonapi/carbonapi.yaml", "error": "open /etc/carbonapi/carbonapi.yaml: no such file or directory"}`

**Comment by Civil** [comment]
Reason behind that is that you anyway would need to tune your config for your setup, so it's not really possible to provide a default config which will work.

Example config should be located in `/usr/share/carbonapi/`

**Comment by Civil** [comment]
Please reopen (or comment) if you think that this behavior should be changed by default. However I'm not that familiar with RHs requirements for the packages and if it is considered to be matricide to not provide a config if it cannot be used as-is in most cases.
