### ISSUE TITLE
0.13.0 release not available in packagecloud

### ISSUE THREAD

**Issue by cjagus** [go-graphite/carbonapi#475]

**Comment by Civil** [comment]
Thanks. I've moved 0.13 for debian-based to stable repo, and I'll look why there is no RH6/7 builds available.

**Comment by Civil** [comment]
Should be fixed now with some caveats.

As I've basically redid the whole build scripts, current release have a version of 0.13.0-0 and starting from now version schema for autobuilds will change.

However now packagecloud have packages for all major distros.

I'll fix the scripts to have a bit more predictable version later (before I'll tag next rc release).
