### ISSUE TITLE
HTTP code 404 instead of 200 for empty result set

### ISSUE THREAD

**Issue by disorder** [go-graphite/carbonapi#483]
When I request target which has no data in defined time period, go-graphite returns empty list "[]" just like graphite-web but status code is 404 instead of 200.

**Comment by Civil** [comment]
What version of carbonapi are you using? And can you please share the config? (you can get current config from /debug/vars http handler)

**Comment by disorder** [comment]
It's Debian buster package  https://packagecloud.io/go-graphite/stable/debian/pool/buster/main/c/carbonapi/carbonapi_0.13.0_amd64.deb

**Comment by lexx-bright** [comment]
@disorder that's expected behaviour according to https://github.com/go-graphite/carbonapi/blob/master/doc/configuration.md#notfoundstatuscode

**Comment by disorder** [comment]
Metrics are found, there is just no data.  Original implementation does return 200 with "[]" content.

**Comment by lexx-bright** [comment]
With "notFoundStatusCode = 200" configuration option it'll work as you expect.

**Comment by Civil** [comment]
@disorder could you please confirm if `notFoundStatusCode` actually fixed your use-case?

**Comment by disorder** [comment]
I did not use it, it's just easier to keep code updated than configuration.  You can close this ticket if your goal is not API compatibility.  In fact we had to move back to original Python implementation because of other open issues which could not be worked around.

**Comment by Civil** [comment]
I've changed default to be `200`. That should fix your use-case for this thing.

As about the other issues you've faced - what were those issues?

**Comment by disorder** [comment]
#434 seems to be working now, #435 would be nice to have and #438 doesn't seem to be fixed.
