### ISSUE TITLE
MaxDataPoints is always sent as 0 to the backend

### ISSUE THREAD

**Issue by JGShaw** [go-graphite/carbonapi#486]
carbonapi does not seem to be populating MaxDataPoints despite it being a field in the [FetchRequest](https://github.com/go-graphite/protocol/blob/master/carbonapi_v3_pb/carbonapi_v3_pb.pb.go#L213). 

We noticed it as we use a custom backend which needs to use the max data points sent from Grafana to decide what resolution of data to query.

**Comment by Civil** [comment]
Yup, that was actually not implemented in carbonapi, but now it should be fixed. Currently this field have same value for all requests, however that might potentially change in future (not sure if that will actually happen though)
