### ISSUE TITLE
Get a list of supported functions

### ISSUE THREAD

**Issue by Nixolay** [go-graphite/carbonapi#491]
Is it possible to get a list of supported functions?

**Comment by Nixolay** [comment]
`func funcIsSupported(funcName string)bool{
	_,ok:=metadata.FunctionMD.Functions[funcName]
	return ok
}`

**Comment by Civil** [comment]
There are two main ways how to do that:
1. https://github.com/go-graphite/carbonapi/blob/main/COMPATIBILITY.md - it is actually generated, but I run generator manually every now and then. Potentially could miss something.
2. carbonapi supports `/functions/` provide a full list of functions that are currently supported.

If you need an easier way to programatically access metadata, feel free to send a PR that would add such API, but it's currently not present and nobody asked for that feature and I cannot come up with any use case for it.
