### ISSUE TITLE
[FR] Remove some moving function suggestions

### ISSUE THREAD

**Issue by jonasbleyl** [go-graphite/carbonapi#520]
When using any of the moving functions (e.g. movingMedian) you get the following suggestions:

    5, 7, 10, 1min, 5min, 10min, 30min, 1hour

The problem with the first 3 is that they don't fetch data before the start-time interval which means that they result in a gap at the beginning of the graph. Carbonapi understandably doesn't handle this like graphite would since it doesn't know the granularity of the data beforehand. The problem is that it is not obvious to the user.

When using Grafana, users will nearly always incorrectly select one of the first options as they appear first in the list without knowing that this will result in a gap.

I can send a pull request if you'd like and if you agree with this minor change.
Thanks!

**Comment by deniszh** [comment]
Hi @jonasbleyl,

> The problem with the first 3 is that they don't fetch data before the start-time interval which means that they result in a gap at the beginning of the graph.

Do you mean intervals < 1 min will not help with graphs where data resolution is >=1 min? That's true, but 1 min resolution is not defined as a standart, and nothing stopping user grom using 10, 5 or even 1 second resolution.
I.e. it's maybe true for your setup, but not always true for all users of this software, hence removing is probably not a good idea. 
Making this configurable is possible, but that will require more efforts, though.

**Comment by jonasbleyl** [comment]
Hi @deniszh,

The gap you would see at the beginning of the graph should appear regardless of the interval your data is in. Even if your data is in 10s intervals and you're applying a movingMedian of 5 it will still require 5 points before the first point can be drawn. When using the time interval (e.g. 5min) carbonapi will purposely query for data 5 minutes prior to the requested time so there won't be a gap at the beginning.

The mistake I made, however, was assuming that 5 was shorthand for 5min but instead it means 5 number of points. So having it appear in the suggestions makes sense so one knows that the function also supports a number of points and not only time.

It's unfortunate that carbonapi doesn't fetch data like graphite does but based on #151 it's because it won't know how far back to query for the extra data.

I'll close this issue as removing the suggestions doesn't seem like the correct solution to this problem.

**Comment by deniszh** [comment]
HI @jonasbleyl,

Yes, sorry, I misunderstood a problem. It's definitely consequence of #151 but I didn't realize that it works differently for number of points and time....
