### ISSUE TITLE
[BUG] Moving median function with an interval less than the interval of the data causes no data to appear

### ISSUE THREAD

**Issue by JGShaw** [go-graphite/carbonapi#522]
When you you apply the moving median function to a series of data with a larger interval than the moving median is over it gives back no data.

For example: 

If the data has points every hour, and you apply `movingMedian(series, '5min')` to it. It causes no data to be returned. Instead it should just return the original data with no medians.

This is causing issues for us when using Grafana, the 1 minutely data for small time range queries needs to have moving median applied, but if the user changes to a larger time range it will use hourly data, causing the moving median function block all of the data from the user.

**Comment by deniszh** [comment]
Probably also related to https://github.com/go-graphite/carbonapi/issues/151
But maybe not - not sure how graphite-web will react on such issue.
