### ISSUE TITLE
Can we use carbonapi in-front of python based graphite?

### ISSUE THREAD

**Issue by ervikrant06** [go-graphite/carbonapi#548]
**Problem description**

First of all sorry for asking configuration related question in this section but I didn't see any option asking for help: 

We are in-process of replacing our existing python graphite stack with go graphite stack on K8s. During the course of this migration I thought of using carbonapi instead of graphite-web with python based graphite for sometime to see the improvements in rendering graphs. We are facing major issue in reading the data from graphite and we are suspecting the issue is coming from python django app. Is't possible to have following type of arrangement?

relay --> python graphite <-- carbonzipper <-- carbonapi   

Also, with recommended go stack can't we use carbon api as graphite-web? 

carbon-c-relay --> go-carbon <-- carbonzipper <-- carbonapi 

When I am putting the carbonapi IP address in browser I can see the following output. can't we create the dashboards like graphite-web.. It's working fine when I am adding carbonapi IP address in grafana as a datasource. 

`supported requests:
    /functions/
    /info/?target=
    /lb_check/
    /metrics/find/?query=
        /render/?target=
        /tags/autoComplete/tags/
    /tags/autoComplete/values/
    /version/
`

Also while trying to fetch the metrics using curl from go-carbon using carbonapi IP address it's not returning anything however I can see the user detail in find output. 

$ curl "http://<CARBON API IPaddress>/metrics/find/?query=condor100.metric.*"
[{"allowChildren":1,"expandable":1,"leaf":0,"id":"user0","text":"user0","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user1","text":"user1","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user2","text":"user2","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user3","text":"user3","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user4","text":"user4","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user5","text":"user5","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user6","text":"user6","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user7","text":"user7","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user8","text":"user8","context":{}},{"allowChildren":1,"expandable":1,"leaf":0,"id":"user9","text":"user9","context":{}}]

Result of following query is nothing ideally it should have shown 

$ curl "http://<CARBON API IPADDR>/render?target=condor100.metric.user1.count"
$

**carbonapi's version**
Version of carbonapi. If you build your own packages, what golang version are you using?

$ curl "http://<CARBON API IPADDR>/version"
1.1.0

**Comment by deniszh** [comment]
Hi @ervikrant06 ,

You can probably put graphite-web as backend for carbonapi, but I doubt that you'll get any performance improvement. Also, carbonzipper now is part of carbonapi, no need to install it as separate component.
go-carbon + carbonapi is working solution too, and in this config you should get some performance improvement.
But please note that carboanapi does not contain nor UI part nor dashboard part from graphite-web, you need some dashboard software like Grafana instead.
Or you can connect graphite-web to same go-carbon:
```
go-carbon <---- carbonapi
                        |
                        -- graphite-web
```
It's also possible to use carbonapi as rendering engine for graphite-web

**Comment by ervikrant06** [comment]
hi @deniszh thanks for your quick and clear reply. is empty output from API is also expected? We rely heavily on checking curl output when data is missing from grafana dashboards. 

$ curl "http:///render?target=condor100.metric.user1.count"
$

**Comment by Civil** [comment]
Append `&format=json` first of all and empty output is expected if carbonapi was built without cario support (`go build` or `make nocairo`, instead of just `make`)

**Comment by ervikrant06** [comment]
Thanks for your comment. I am not versed with go lang. Thought of changing simple `make` with `make nocairo` it failed the docker build image part

`FROM golang:1.15.3-alpine3.12 AS build

ARG gocarbon_version=0.15.5
ARG gocarbon_repo=https://github.com/go-graphite/go-carbon.git
RUN apk add --update git make \
 && git clone "${gocarbon_repo}" /usr/local/src/go-carbon \
 && cd /usr/local/src/go-carbon \
 && git checkout tags/v"${gocarbon_version}" \
 #&& make \
 && make nocairo \
 && chmod +x go-carbon && cp -fv go-carbon /tmp
`

Error from docker file

`fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.41.0-r0)
(2/6) Installing libcurl (7.69.1-r3)
(3/6) Installing expat (2.2.9-r1)
(4/6) Installing pcre2 (10.35-r0)
(5/6) Installing git (2.26.2-r0)
(6/6) Installing make (4.3-r0)
Executing busybox-1.31.1-r19.trigger
OK: 22 MiB in 21 packages
Cloning into '/usr/local/src/go-carbon'...
Note: switching to 'tags/v0.15.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d216826 0.15.5 (#386)
make: *** No rule to make target 'nocairo'.  Stop.
`

**Comment by Civil** [comment]
`nocairo` is not for go-carbon, but for carbonapi itself.

carbonapi support two modes:
1. `make nocairo` (or `go get -u github.com/go-graphite/carbonapi/cmd/carbonapi`) - then carboapi will be built without cairo support (that means that `&format=png` or `&format=svg` won't work, and png is a default format anyway)
2. `make` in the top level of carbonapi git directory would build it with cairo support (you would need to have libcairo installed to build it). Then `png` and `svg` will work and requests without format will return png graphs back.

Actually I can make a change to make default format configurable to make it simplier, shouldn'be that hard.

**Comment by ervikrant06** [comment]
My apologies for not noticing carbonapi. I am using default Docker file available at https://github.com/go-graphite/carbonapi/blob/main/Dockerfile It has by default `make nocairo` statement which should return with `&format=json` right.. but it also return empty result. Sorry if I am missing something.

**Comment by ervikrant06** [comment]
> Hi @ervikrant06 ,
> 
> You can probably put graphite-web as backend for carbonapi, but I doubt that you'll get any performance improvement. Also, carbonzipper now is part of carbonapi, no need to install it as separate component.
> go-carbon + carbonapi is working solution too, and in this config you should get some performance improvement.
> But please note that carboanapi does not contain nor UI part nor dashboard part from graphite-web, you need some dashboard software like Grafana instead.
> Or you can connect graphite-web to same go-carbon:
> 
> ```
> go-carbon <---- carbonapi
>               |
>               -- graphite-web
> ```
> 
> It's also possible to use carbonapi as rendering engine for graphite-web

We are mainly facing issue with read performance. One more question to minimize the changes in setup: Isn't possible to use carbonapi and/or carbonzipper as a frontend for carbon-cache directory instead of using go-carbon+graphite-web stack.

**Comment by Civil** [comment]
Hm, I got an email about reply from @ervikrant06 in this ticket, but I can't see in the web-interface.

And the question there was:
> We are mainly facing issue with read performance. One more question to minimize the changes in setup: Isn't possible to use carbonapi and/or carbonzipper as a frontend for carbon-cache directory instead of using go-carbon+graphite-web stack.

If that's still the question - the answer is "no". Carbonapi cannot read directly from whisper files and it cannot speak carbonlink protocol. It can use graphite-web as a backend (if graphite-web is recent enough and supports msgpack, so any 1.1.0+ should work) but that's not really well tested as it won't have huge performance advantage over pure graphite-web (msgpack was implemented in a first place because of metrictank).

So for performance benefits there is no easy solution to that, you either will need to migrate to go-carbon (as a replacement for carboncache), but go-carbon doesn't support tags (if that's important for you) or to migrate away from whisper to something like carbon-clickhouse/graphite-clickhouse or victoriametrics.

> But please note that carboanapi does not contain nor UI part nor dashboard part from graphite-web, you need some dashboard software like Grafana instead.

You can have graphite-web and setup nginx to proxy-pass /metrics and /render to carbonapi, that way you'll have a working graphite-web on top of carbonapi. Or you can use https://github.com/lomik/graphite-web-ui which is fork of graphite-web by Lomik that doesn't have any dynamic features (like it's own dashboards).

**Comment by ervikrant06** [comment]
Thanks a lot for your detailed explanation. Ya initially I added the comment after re-reading the thread I realized I already had a answer about the compatiblity. We will plan to switch the stack completely to go.. BTW we don't need tag support. 

Still I am juggling to enable the API stuff on carbonapi. I just need a json output result from the carbonapi. I don't need any UI facility. 

Explaning about our use case of APIs: Based on the grafana alert, we are using using curl to hit the graphite-web to get the information about some users and take action on them. It's important part of our workflow.

**Comment by Civil** [comment]
With go-carbon you can at first replace carbon-cache with it and give it a test. graphite-web can read from go-carbon (go-carbon supports both carbonlink and you can use CLUSTER_SERVER option to point it to carbonserver module of go-carbon). And after you are happy with how it works, then you can replace graphite-web with carbonapi.

**Comment by ervikrant06** [comment]
thanks for your comment, actually I was looking for some inputs on this comment https://github.com/go-graphite/carbonapi/issues/548#issuecomment-748078555  still I am not able to get the results using API. I have created carbonapi container using default Dockerfile.

**Comment by Civil** [comment]
> thanks for your comment, actually I was looking for some inputs on this comment #548 (comment) still I am not able to get the results using API. I have created carbonapi container using default Dockerfile.


For that part question is what's in the logs of carbonapi and what are the response headers?

**Comment by ervikrant06** [comment]
i guess i have found the issue, I am using K8s to deploy this setup. LB service is setup for carbonAPI running only pod of carbonapi for now. this is my carbonapi configuration: Each of the upstream server is K8s service with go-carbon endpoint. I am writing the metrics through carbon-c-relay, it's distributing the metrics across three go-carbon PODs. Each of this POD is endpoing for the service mentioned in upstream list of below carbonapi conf. 

~~~
listen: "0.0.0.0:8081"
concurency: 20
cache:
  # Type of caching. Valid: "mem", "memcache", "null"
  type: "mem"
upstreams:
  backendsv2:
    backends:
      -
        protocol: "carbonapi_v3_pb"
        lbMethod: "broadcast"
        servers:
          - "http://cache-testsvc-1:8080"
          - "http://cache-testsvc-2:8080"
          - "http://cache-testsvc-3:8080"
~~~


When I am using carbonapi as a datasource in grafana. I can see the stats from all three go-carbon instances. When I am hitting the same carbonapi address using API it's only fetching the results from the first server in the list. Ideally it  should return the results from all three.

**Comment by Civil** [comment]
Grafana uses the same API that you are trying to use with curl, so there shouldn't be any difference in a way how request works, unless 2 out of 3 backends were unavailable at the time of a query.

**Comment by ervikrant06** [comment]
thanks it's working fine. Not sure it took some time to reflect the stats.
