### ISSUE TITLE
[FR] 0.14.2 not pushed to package cloud

### ISSUE THREAD

**Issue by Hipska** [go-graphite/carbonapi#564]
The latest pushed version seems to be 0.14.1

https://packagecloud.io/app/go-graphite/stable/search?q=carbonapi&filter=all&filter=all&dist=

**Comment by Civil** [comment]
Right... I'll have a look at why the packaging script doesn't work now. Maybe that would actually make me move this portion away from travis and make it easier to use.

**Comment by Civil** [comment]
It seems to be working now for 0.15.0. Not sure what was the problem back then to be honest...

**Comment by Felixoid** [comment]
https://travis-ci.org/github/go-graphite/carbonapi/builds/745295109  
It's marked as canceled in travis https://travis-ci.org/github/go-graphite/carbonapi/builds/745295109

On another hand, 0.14.2.1 is marked as successful https://travis-ci.org/github/go-graphite/carbonapi/jobs/745296463
