### ISSUE TITLE
[BUG] carbonapi metric finder results cannot be read by graphite-web running on python3

### ISSUE THREAD

**Issue by drawks** [go-graphite/carbonapi#597]
**Describe the bug**
Related to https://github.com/graphite-project/graphite-web/issues/2692 the pickled object returns from `/metrics/find` cannot be deserialized by graphite-web running on python-3

**CarbonAPI Version**
tested with 0.12.3 and 0.15.2

**Simplified query (if applicable)**
```
$ curl -s 'http://graphite.internal.server:8000/metrics/find?local=1&format=pickle&query=%2A'|python3 -c 'import pickle, sys; pickle.loads(sys.stdin.buffer.read())'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'Interval' object has no attribute '__dict__'
```

**Additional context**
This appears to be caused by the different way that slotted objects are handled in python2 vs python3. The objects returned by carbonapi appear to replicate what is returned by graphite-web 1.x running on python 2.x which cannot be unpickled py graphite-web 1.x running on python 3.x

**Comment by reyjrar** [comment]
A work-around is to set `graphite09compat`, but I'm not sure what other side effects that has when running graphite-1.1.x with graphite09compat enabled.

**Comment by drawks** [comment]
I've got an MR open against graphite-web to solve this on their end. It would be good if carbonapi/og-rek had some obvious way of creating slotted objects, but this should sort things for now.

**Comment by drawks** [comment]
This issue should be resolved in the next release of graphite-web.
