### ISSUE TITLE
Find() for victoriametrics

### ISSUE THREAD

**Issue by ikod** [go-graphite/carbonapi#634]
Hi,

Why  after this check
https://github.com/go-graphite/carbonapi/blob/4d91ac267a797888da43ec427fa6972affdc5712/zipper/protocols/victoriametrics/find.go#L19

carbonapi anyway try to use  prometheus api instead of graphite as per victoriamectrics docs (for single node):
https://github.com/VictoriaMetrics/VictoriaMetrics#graphite-metrics-api-usage
or (for cluster)
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format

**Comment by Civil** [comment]
I don't exactly remember why, as that's changed about 6 months ago, but as far as I remember Victoria Metrics at that time supported /metrics/expand API (but not metrics/find which are different) and that in reality worked worse, so it was rewritten to use prometheus style API anyway.

`/metrics/find` API is newer than the support implementation and before I looked again at the link you've provided I wasn't aware they even support it.

**Comment by ikod** [comment]
Hi @Civil 
Thanks for response!
I'll try to rewrite it to use '/metrics/find' call and submit PR if you have no objections.

**Comment by Civil** [comment]
Yeah, sure, I would be happy to accept it.

If that's not too much hassle, I would suggest to use the same parser pool (that's github.com/valyala/fastjson). It is a bit harder to use, but seems to be much faster for the sake of parsing huge replies.

**Comment by Civil** [comment]
Oh, and one more thing, it would be great if you'll also bump the version requirement for victoria metrics to match the first release that had `metrics/find` API

**Comment by ikod** [comment]
> Yeah, sure, I would be happy to accept it.
> 
> If that's not too much hassle, I would suggest to use the same parser pool (that's github.com/valyala/fastjson). It is a bit harder to use, but seems to be much faster for the sake of parsing huge replies.

Right now, I think forwarding VM response  without parsing is enough. But I'll look closer into it a bit later.

> Oh, and one more thing, it would be great if you'll also bump the version requirement for victoria metrics to match the first release that had `metrics/find` API

Ok!

**Comment by ikod** [comment]
Just for record
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.41.0

FEATURE: initial implementation of Graphite Metrics API - see these docs.

**Comment by Civil** [comment]
Initial implementaition, as far as I remember, lacked compatible implementation of /metrics/find. So if it was fixed to work - that should happen in one of the following versions (AFAIR it supported only expand API that is used in graphite-web to create metric tree)

However there is a chance that I do not remember that correclty

**Comment by Civil** [comment]
AFAIR that was fully fixed here:
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/6fdfc67620bd8c86c1b0c992eb8e1cd029a3a9b0

That should be one of the next releases (1.42.0 maybe?)

**Comment by ikod** [comment]
Thanks!
