### ISSUE TITLE
[BUG] aliasByTags() function works wrong on metrics with "(" ")" in tag values

### ISSUE THREAD

**Issue by newsett1er** [go-graphite/carbonapi#650]
After upgrading from 0.14.0 to 0.15.4. aliasByTags() returns only part to ")", not full tag. Second and next tags are ignored.

**CarbonAPI Version**
0.15.4

query:
seriesByTag('name=robots.RobotsActivity', 'event=NewFeature', 'robot=~bot (etl)', 'sub_metric=allowed_delay')
returns as Target:

robots.RobotsActivity;agg_func=anyLast;event=NewFeature;interval=60s;offset=;robot=bot (etl);sub_metric=allowed_delay

query:
aliasByTags(consolidateBy(seriesByTag('name=robots.RobotsActivity', 'event=NewTender', 'robot=~bot (etl)', 'sub_metric=allowed_delay'), 'last'), 'robot', 'event', 'sub_metric', 'offset') 

returns as Target:
bot (etl

**Comment by Civil** [comment]
Theoretically that should be fixed in current master. If you can check if that works for you, it would be great.

If it's not - please reopen the issue.
