### ISSUE TITLE
Symlink support

### ISSUE THREAD

**Issue by gerases** [go-graphite/carbonapi#668]
I can't easily find an answer to this quick question: are symlinks to whisper files supported? For example, if I have a symlink named `x.wsp` pointing to `../y.wsp`, will that work?

According to my quick tests they are not, but I might be wrong. So asking in case there's a well known answer to this.

Thanks!

**Comment by deniszh** [comment]
Hi @gerases 

Carbonapi is a frontend, it doesn't support whisper files. Which backend do you use, go-carbon? It's better to open issue [there](https://github.com/go-graphite/go-carbon/issues) instead.

**Comment by gerases** [comment]
Thank you for the tip, @deniszh. I'll ask there!
