### ISSUE TITLE
carbonapi handles missing metrics differently to graphite

### ISSUE THREAD

**Issue by xsist10** [go-graphite/carbonapi#90]
If you specify a missing metric as part of a larger formula, the query will fail in carbonapi but succeed in Graphite.

A simple example of this is:

```
data.metric1  # Exists
data.metric2  # Does not exists

diffSeries(data.metric1, data.metric2) # Fails on carbonapi
diffSeries(data.metric1, transformNull(data.metric2, 0)) # Also fails on carbonapi
```

I would expect the result to be `data.metric1` since I'd assume that `data.metric1 - [undefined]` would equal `data.metric1`.

A valid use case in this situation is as followed:

```
# Metric layout
page.[page_name].requests
page.[page_name].errors

# The number of total successful pages served (number of requests - number of errors)
# If we automate this in any form we may hit a page that has never had an error recorded.
diffSeries(page.index_html.requests, page.index_html.errors) 
```

**Comment by Civil** [comment]
I understand that a lot of time passed since you've opened this bug. But I'd still want to ask if you know that it's still valid?

**Comment by azhiltsov** [comment]
Yes it still valid.
/render/?target=sumSeries(test.exist,test.inexist)&format=json return empty json
It seems to be an edge case for #161 but should be easier to fix
